name: by_faith
title: By Faith
description: "A New Christian Missions app."
publish_to: 'none'

version: 3.0.0

environment:
  sdk: 3.8.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: 1.0.8
  material_symbols_icons: ^4.2815.1
  intl: 0.20.2
  provider: ^6.1.5
  flutter_quill: 11.4.1
  objectbox: 4.3.0
  objectbox_flutter_libs: 4.3.0
  flutter_map: 8.1.1
  flutter_map_tile_caching: 11.0.0-dev.2
  latlong2: 0.9.1
  path_provider: 2.1.5
  http: ^1.4.0
  archive: 3.6.1
  file_picker: 10.1.9
  url_launcher: 6.3.1
  permission_handler: 12.0.0+1
  quill_delta: 3.0.0-nullsafety.2 # Explicitly add quill_delta
  share_plus: 11.0.0
  connectivity_plus: ^6.1.4
  onboarding: 4.0.2
  font_awesome_flutter: ^10.8.0
  characters: 1.4.0
  collection: ^1.19.1
  vector_math: 2.1.4
  uuid: 3.0.7
  fastforge: 0.5.1
  fl_chart: 1.0.0
  flutter_map_animations: 0.9.0
  flutter_dotenv: 5.2.1
  cached_network_image: 3.3.1
  flutter_local_notifications: 19.2.1
  table_calendar: 3.2.0
  reactive_mind_map: 1.0.2

dev_dependencies:
  build_runner: ^2.4.15
  flutter_test:
    sdk: flutter
  flutter_lints: 6.0.0
  flutter_app_packager: any
  objectbox_generator: 4.3.0

flutter:
  uses-material-design: true
  assets:
    - .env
    - lib/features/go/assets/images/marker.png