name: by_faith
title: By Faith
description: "A New Christian Missions app."
publish_to: 'none'

version: 3.1.2

environment:
  sdk: 3.8.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: 1.0.8
  material_symbols_icons: ^4.2815.1
  intl: 0.20.2
  provider: ^6.1.5
  flutter_quill: 11.4.1
  flutter_quill_extensions: ^11.0.0 # Downgrade to suggested version
  quill_delta: 3.0.0-nullsafety.2 # Explicitly add quill_delta
  objectbox: 4.3.0
  objectbox_flutter_libs: 4.3.0
  flutter_map: ^8.1.1
  flutter_map_tile_caching: ^11.0.0-dev.2
  flutter_map_line_editor: ^8.0.0
  flutter_map_dragmarker: ^8.0.3
  flutter_map_animations: 0.9.0
  latlong2: 0.9.1
  path_provider: 2.1.5
  path: ^1.8.0
  http: ^1.4.0
  archive: 3.6.1
  file_picker: ^10.2.0
  url_launcher: 6.3.1
  bible_parser_flutter: 0.1.0 # Freezing Updates forked source 
  xml: ^6.5.0 # Added for XML parsing
  permission_handler: 12.0.0+1
  share_plus: 11.0.0
  connectivity_plus: ^6.0.5
  onboarding: 4.0.2
  font_awesome_flutter: ^10.8.0
  characters: 1.4.0
  collection: ^1.19.1
  vector_math: 2.1.4
  uuid: 3.0.7
  fastforge: ^0.6.0
  fl_chart: 1.0.0
  flutter_dotenv: 5.2.1
  cached_network_image: 3.3.1
  flutter_local_notifications: 19.2.1
  table_calendar: 3.2.0
  reactive_mind_map: ^1.0.3
  slang: ^4.7.2
  slang_flutter: ^4.7.0
  flutter_localizations: # Add flutter_localizations
    sdk: flutter


dev_dependencies:
  build_runner: ^2.4.15
  flutter_test:
    sdk: flutter
  flutter_lints: 6.0.0
  flutter_app_packager: any
  objectbox_generator: 4.3.0
  slang_build_runner: ^4.7.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - .env
    - lib/features/go/assets/images/marker_person.png
    - lib/features/go/assets/images/marker_church.png
    - lib/features/go/assets/images/marker_ministry.png
