// GENERATED CODE - DO NOT MODIFY BY HAND
// This code was generated by ObjectBox. To update it run the generator again
// with `dart run build_runner build`.
// See also https://docs.objectbox.io/getting-started#generate-objectbox-code

// ignore_for_file: camel_case_types, depend_on_referenced_packages
// coverage:ignore-file

import 'dart:typed_data';

import 'package:flat_buffers/flat_buffers.dart' as fb;
import 'package:objectbox/internal.dart'
    as obx_int; // generated code can access "internal" functionality
import 'package:objectbox/objectbox.dart' as obx;
import 'package:objectbox_flutter_libs/objectbox_flutter_libs.dart';

import 'core/models/user_preferences_model.dart';
import 'features/go/models/go_map_info_model.dart';
import 'features/go/models/go_model.dart';
import 'features/go/models/go_route_models.dart';

export 'package:objectbox/objectbox.dart'; // so that callers only have to import this file

final _entities = <obx_int.ModelEntity>[
  obx_int.ModelEntity(
    id: const obx_int.IdUid(1, 5934710014868510144),
    name: 'GoArea',
    lastPropertyId: const obx_int.IdUid(4, 4719810631407430190),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 4735014348236256782),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 5270290642780277915),
        name: 'name',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 2303379501014807280),
        name: 'latitudes',
        type: 29,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 4719810631407430190),
        name: 'longitudes',
        type: 29,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(2, 2976838995681299634),
    name: 'GoChurch',
    lastPropertyId: const obx_int.IdUid(9, 1209198672196407328),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 968884686896920005),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 312982000459823389),
        name: 'churchName',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 269052675674822294),
        name: 'pastorName',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 7053965391135739371),
        name: 'address',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 5215084230748986214),
        name: 'phone',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 1088852850630062593),
        name: 'email',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 4750274700031141464),
        name: 'latitude',
        type: 8,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(8, 177805016467694205),
        name: 'longitude',
        type: 8,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(9, 1209198672196407328),
        name: 'financialStatus',
        type: 9,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[
      obx_int.ModelRelation(
        id: const obx_int.IdUid(1, 693632190060815477),
        name: 'notes',
        targetId: const obx_int.IdUid(3, 8557193571509810339),
      ),
    ],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(3, 8557193571509810339),
    name: 'GoChurchNote',
    lastPropertyId: const obx_int.IdUid(5, 2034842985780451852),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 7324540023115484490),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 7640711063533775918),
        name: 'content',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 1900413642208290839),
        name: 'createdAt',
        type: 10,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 5120808221296115053),
        name: 'updatedAt',
        type: 10,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 2034842985780451852),
        name: 'churchId',
        type: 11,
        flags: 520,
        indexId: const obx_int.IdUid(1, 6574804566610795733),
        relationTarget: 'GoChurch',
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(4, 1563122691308849417),
    name: 'GoContact',
    lastPropertyId: const obx_int.IdUid(10, 3031340471001851166),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 4345750754156132435),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 4875675498399401256),
        name: 'fullName',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 3739273668718633689),
        name: 'latitude',
        type: 8,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 8326119360039659684),
        name: 'longitude',
        type: 8,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 7152010175276004202),
        name: 'address',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 4059129177120214785),
        name: 'birthday',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 2465454937046751996),
        name: 'phone',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(8, 1470393389381585199),
        name: 'email',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(9, 326899297598335523),
        name: 'isVisited',
        type: 1,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(10, 3031340471001851166),
        name: 'eternalStatus',
        type: 9,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[
      obx_int.ModelRelation(
        id: const obx_int.IdUid(2, 8635122689219090283),
        name: 'notes',
        targetId: const obx_int.IdUid(5, 2793593010617758502),
      ),
    ],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(5, 2793593010617758502),
    name: 'GoContactNote',
    lastPropertyId: const obx_int.IdUid(5, 6512056552659136612),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 3775084897952015777),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 7710246386290331508),
        name: 'content',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 848322645834637263),
        name: 'createdAt',
        type: 10,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 8801844033008023918),
        name: 'updatedAt',
        type: 10,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 6512056552659136612),
        name: 'contactId',
        type: 11,
        flags: 520,
        indexId: const obx_int.IdUid(2, 8117297475634584705),
        relationTarget: 'GoContact',
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(6, 5070628996559534998),
    name: 'GoMapInfo',
    lastPropertyId: const obx_int.IdUid(8, 6314048032745272492),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 4096888978004063649),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 4643176127824311866),
        name: 'name',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 3445818165968073067),
        name: 'filePath',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 3582043772416612364),
        name: 'downloadUrl',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 6205585862838643800),
        name: 'isTemporary',
        type: 1,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 76014413259626933),
        name: 'latitude',
        type: 8,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 8511324361783724165),
        name: 'longitude',
        type: 8,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(8, 6314048032745272492),
        name: 'zoomLevel',
        type: 6,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(7, 3930338461992071846),
    name: 'GoMinistry',
    lastPropertyId: const obx_int.IdUid(9, 8463971852427811193),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 7300966489314760403),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 8530294532571799573),
        name: 'ministryName',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 5672915997604998889),
        name: 'contactName',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 8068828976007574316),
        name: 'address',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 4903791859278077257),
        name: 'phone',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 2513372957446418785),
        name: 'email',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 5346886106986558255),
        name: 'latitude',
        type: 8,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(8, 3456910104211604558),
        name: 'longitude',
        type: 8,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(9, 8463971852427811193),
        name: 'partnerStatus',
        type: 9,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[
      obx_int.ModelRelation(
        id: const obx_int.IdUid(3, 8002177189385325552),
        name: 'notes',
        targetId: const obx_int.IdUid(8, 4202181766675305731),
      ),
    ],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(8, 4202181766675305731),
    name: 'GoMinistryNote',
    lastPropertyId: const obx_int.IdUid(5, 3308290267393319786),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 3648250398510020208),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 1974864320198232344),
        name: 'content',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 4543644955035434797),
        name: 'createdAt',
        type: 10,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 6955782507361437326),
        name: 'updatedAt',
        type: 10,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 3308290267393319786),
        name: 'ministryId',
        type: 11,
        flags: 520,
        indexId: const obx_int.IdUid(3, 4156189790569410301),
        relationTarget: 'GoMinistry',
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(9, 2847472749571886678),
    name: 'GoStreet',
    lastPropertyId: const obx_int.IdUid(5, 499884117723718130),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 8769311169360605969),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 4144176335540429422),
        name: 'name',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 5439737961643073816),
        name: 'latitudes',
        type: 29,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 7241142737842961668),
        name: 'longitudes',
        type: 29,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 499884117723718130),
        name: 'type',
        type: 9,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(10, 4601432361066733175),
    name: 'GoZone',
    lastPropertyId: const obx_int.IdUid(6, 5660241697865258407),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 2001314730310083714),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 7921063889054115614),
        name: 'name',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 8650267128399791391),
        name: 'latitude',
        type: 8,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 1623256598045066766),
        name: 'longitude',
        type: 8,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 1886101980102643131),
        name: 'widthInMeters',
        type: 8,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 5660241697865258407),
        name: 'heightInMeters',
        type: 8,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(11, 3993733589777755805),
    name: 'UserPreferences',
    lastPropertyId: const obx_int.IdUid(4, 4944652992825156040),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 7235213291390302949),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 723924164939195479),
        name: 'currentMap',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 8580107311452247288),
        name: 'fontFamily',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 4944652992825156040),
        name: 'fontSize',
        type: 8,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
];

/// Shortcut for [obx.Store.new] that passes [getObjectBoxModel] and for Flutter
/// apps by default a [directory] using `defaultStoreDirectory()` from the
/// ObjectBox Flutter library.
///
/// Note: for desktop apps it is recommended to specify a unique [directory].
///
/// See [obx.Store.new] for an explanation of all parameters.
///
/// For Flutter apps, also calls `loadObjectBoxLibraryAndroidCompat()` from
/// the ObjectBox Flutter library to fix loading the native ObjectBox library
/// on Android 6 and older.
Future<obx.Store> openStore({
  String? directory,
  int? maxDBSizeInKB,
  int? maxDataSizeInKB,
  int? fileMode,
  int? maxReaders,
  bool queriesCaseSensitiveDefault = true,
  String? macosApplicationGroup,
}) async {
  await loadObjectBoxLibraryAndroidCompat();
  return obx.Store(
    getObjectBoxModel(),
    directory: directory ?? (await defaultStoreDirectory()).path,
    maxDBSizeInKB: maxDBSizeInKB,
    maxDataSizeInKB: maxDataSizeInKB,
    fileMode: fileMode,
    maxReaders: maxReaders,
    queriesCaseSensitiveDefault: queriesCaseSensitiveDefault,
    macosApplicationGroup: macosApplicationGroup,
  );
}

/// Returns the ObjectBox model definition for this project for use with
/// [obx.Store.new].
obx_int.ModelDefinition getObjectBoxModel() {
  final model = obx_int.ModelInfo(
    entities: _entities,
    lastEntityId: const obx_int.IdUid(11, 3993733589777755805),
    lastIndexId: const obx_int.IdUid(3, 4156189790569410301),
    lastRelationId: const obx_int.IdUid(3, 8002177189385325552),
    lastSequenceId: const obx_int.IdUid(0, 0),
    retiredEntityUids: const [],
    retiredIndexUids: const [],
    retiredPropertyUids: const [],
    retiredRelationUids: const [],
    modelVersion: 5,
    modelVersionParserMinimum: 5,
    version: 1,
  );

  final bindings = <Type, obx_int.EntityDefinition>{
    GoArea: obx_int.EntityDefinition<GoArea>(
      model: _entities[0],
      toOneRelations: (GoArea object) => [],
      toManyRelations: (GoArea object) => {},
      getId: (GoArea object) => object.id,
      setId: (GoArea object, int id) {
        object.id = id;
      },
      objectToFB: (GoArea object, fb.Builder fbb) {
        final nameOffset = fbb.writeString(object.name);
        final latitudesOffset = fbb.writeListFloat64(object.latitudes);
        final longitudesOffset = fbb.writeListFloat64(object.longitudes);
        fbb.startTable(5);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, nameOffset);
        fbb.addOffset(2, latitudesOffset);
        fbb.addOffset(3, longitudesOffset);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final nameParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final latitudesParam = const fb.ListReader<double>(
          fb.Float64Reader(),
          lazy: false,
        ).vTableGet(buffer, rootOffset, 8, []);
        final longitudesParam = const fb.ListReader<double>(
          fb.Float64Reader(),
          lazy: false,
        ).vTableGet(buffer, rootOffset, 10, []);
        final object = GoArea(
          id: idParam,
          name: nameParam,
          latitudes: latitudesParam,
          longitudes: longitudesParam,
        );

        return object;
      },
    ),
    GoChurch: obx_int.EntityDefinition<GoChurch>(
      model: _entities[1],
      toOneRelations: (GoChurch object) => [],
      toManyRelations: (GoChurch object) => {
        obx_int.RelInfo<GoChurch>.toMany(1, object.id): object.notes,
      },
      getId: (GoChurch object) => object.id,
      setId: (GoChurch object, int id) {
        object.id = id;
      },
      objectToFB: (GoChurch object, fb.Builder fbb) {
        final churchNameOffset = fbb.writeString(object.churchName);
        final pastorNameOffset = object.pastorName == null
            ? null
            : fbb.writeString(object.pastorName!);
        final addressOffset = object.address == null
            ? null
            : fbb.writeString(object.address!);
        final phoneOffset = object.phone == null
            ? null
            : fbb.writeString(object.phone!);
        final emailOffset = object.email == null
            ? null
            : fbb.writeString(object.email!);
        final financialStatusOffset = object.financialStatus == null
            ? null
            : fbb.writeString(object.financialStatus!);
        fbb.startTable(10);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, churchNameOffset);
        fbb.addOffset(2, pastorNameOffset);
        fbb.addOffset(3, addressOffset);
        fbb.addOffset(4, phoneOffset);
        fbb.addOffset(5, emailOffset);
        fbb.addFloat64(6, object.latitude);
        fbb.addFloat64(7, object.longitude);
        fbb.addOffset(8, financialStatusOffset);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final churchNameParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final pastorNameParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 8);
        final addressParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 10);
        final phoneParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 12);
        final emailParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 14);
        final latitudeParam = const fb.Float64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          16,
        );
        final longitudeParam = const fb.Float64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          18,
        );
        final financialStatusParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 20);
        final object = GoChurch(
          id: idParam,
          churchName: churchNameParam,
          pastorName: pastorNameParam,
          address: addressParam,
          phone: phoneParam,
          email: emailParam,
          latitude: latitudeParam,
          longitude: longitudeParam,
          financialStatus: financialStatusParam,
        );
        obx_int.InternalToManyAccess.setRelInfo<GoChurch>(
          object.notes,
          store,
          obx_int.RelInfo<GoChurch>.toMany(1, object.id),
        );
        return object;
      },
    ),
    GoChurchNote: obx_int.EntityDefinition<GoChurchNote>(
      model: _entities[2],
      toOneRelations: (GoChurchNote object) => [object.church],
      toManyRelations: (GoChurchNote object) => {},
      getId: (GoChurchNote object) => object.id,
      setId: (GoChurchNote object, int id) {
        object.id = id;
      },
      objectToFB: (GoChurchNote object, fb.Builder fbb) {
        final contentOffset = fbb.writeString(object.content);
        fbb.startTable(6);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, contentOffset);
        fbb.addInt64(2, object.createdAt.millisecondsSinceEpoch);
        fbb.addInt64(3, object.updatedAt?.millisecondsSinceEpoch);
        fbb.addInt64(4, object.church.targetId);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final updatedAtValue = const fb.Int64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          10,
        );
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final contentParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final createdAtParam = DateTime.fromMillisecondsSinceEpoch(
          const fb.Int64Reader().vTableGet(buffer, rootOffset, 8, 0),
        );
        final updatedAtParam = updatedAtValue == null
            ? null
            : DateTime.fromMillisecondsSinceEpoch(updatedAtValue);
        final object = GoChurchNote(
          id: idParam,
          content: contentParam,
          createdAt: createdAtParam,
          updatedAt: updatedAtParam,
        );
        object.church.targetId = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          12,
          0,
        );
        object.church.attach(store);
        return object;
      },
    ),
    GoContact: obx_int.EntityDefinition<GoContact>(
      model: _entities[3],
      toOneRelations: (GoContact object) => [],
      toManyRelations: (GoContact object) => {
        obx_int.RelInfo<GoContact>.toMany(2, object.id): object.notes,
      },
      getId: (GoContact object) => object.id,
      setId: (GoContact object, int id) {
        object.id = id;
      },
      objectToFB: (GoContact object, fb.Builder fbb) {
        final fullNameOffset = fbb.writeString(object.fullName);
        final addressOffset = object.address == null
            ? null
            : fbb.writeString(object.address!);
        final birthdayOffset = object.birthday == null
            ? null
            : fbb.writeString(object.birthday!);
        final phoneOffset = object.phone == null
            ? null
            : fbb.writeString(object.phone!);
        final emailOffset = object.email == null
            ? null
            : fbb.writeString(object.email!);
        final eternalStatusOffset = object.eternalStatus == null
            ? null
            : fbb.writeString(object.eternalStatus!);
        fbb.startTable(11);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, fullNameOffset);
        fbb.addFloat64(2, object.latitude);
        fbb.addFloat64(3, object.longitude);
        fbb.addOffset(4, addressOffset);
        fbb.addOffset(5, birthdayOffset);
        fbb.addOffset(6, phoneOffset);
        fbb.addOffset(7, emailOffset);
        fbb.addBool(8, object.isVisited);
        fbb.addOffset(9, eternalStatusOffset);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final fullNameParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final latitudeParam = const fb.Float64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          8,
        );
        final longitudeParam = const fb.Float64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          10,
        );
        final addressParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 12);
        final birthdayParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 14);
        final phoneParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 16);
        final emailParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 18);
        final isVisitedParam = const fb.BoolReader().vTableGet(
          buffer,
          rootOffset,
          20,
          false,
        );
        final eternalStatusParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 22);
        final object = GoContact(
          id: idParam,
          fullName: fullNameParam,
          latitude: latitudeParam,
          longitude: longitudeParam,
          address: addressParam,
          birthday: birthdayParam,
          phone: phoneParam,
          email: emailParam,
          isVisited: isVisitedParam,
          eternalStatus: eternalStatusParam,
        );
        obx_int.InternalToManyAccess.setRelInfo<GoContact>(
          object.notes,
          store,
          obx_int.RelInfo<GoContact>.toMany(2, object.id),
        );
        return object;
      },
    ),
    GoContactNote: obx_int.EntityDefinition<GoContactNote>(
      model: _entities[4],
      toOneRelations: (GoContactNote object) => [object.contact],
      toManyRelations: (GoContactNote object) => {},
      getId: (GoContactNote object) => object.id,
      setId: (GoContactNote object, int id) {
        object.id = id;
      },
      objectToFB: (GoContactNote object, fb.Builder fbb) {
        final contentOffset = fbb.writeString(object.content);
        fbb.startTable(6);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, contentOffset);
        fbb.addInt64(2, object.createdAt.millisecondsSinceEpoch);
        fbb.addInt64(3, object.updatedAt?.millisecondsSinceEpoch);
        fbb.addInt64(4, object.contact.targetId);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final updatedAtValue = const fb.Int64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          10,
        );
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final contentParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final createdAtParam = DateTime.fromMillisecondsSinceEpoch(
          const fb.Int64Reader().vTableGet(buffer, rootOffset, 8, 0),
        );
        final updatedAtParam = updatedAtValue == null
            ? null
            : DateTime.fromMillisecondsSinceEpoch(updatedAtValue);
        final object = GoContactNote(
          id: idParam,
          content: contentParam,
          createdAt: createdAtParam,
          updatedAt: updatedAtParam,
        );
        object.contact.targetId = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          12,
          0,
        );
        object.contact.attach(store);
        return object;
      },
    ),
    GoMapInfo: obx_int.EntityDefinition<GoMapInfo>(
      model: _entities[5],
      toOneRelations: (GoMapInfo object) => [],
      toManyRelations: (GoMapInfo object) => {},
      getId: (GoMapInfo object) => object.id,
      setId: (GoMapInfo object, int id) {
        object.id = id;
      },
      objectToFB: (GoMapInfo object, fb.Builder fbb) {
        final nameOffset = fbb.writeString(object.name);
        final filePathOffset = object.filePath == null
            ? null
            : fbb.writeString(object.filePath!);
        final downloadUrlOffset = object.downloadUrl == null
            ? null
            : fbb.writeString(object.downloadUrl!);
        fbb.startTable(9);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, nameOffset);
        fbb.addOffset(2, filePathOffset);
        fbb.addOffset(3, downloadUrlOffset);
        fbb.addBool(4, object.isTemporary);
        fbb.addFloat64(5, object.latitude);
        fbb.addFloat64(6, object.longitude);
        fbb.addInt64(7, object.zoomLevel);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final nameParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final filePathParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 8);
        final downloadUrlParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 10);
        final isTemporaryParam = const fb.BoolReader().vTableGetNullable(
          buffer,
          rootOffset,
          12,
        );
        final latitudeParam = const fb.Float64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          14,
        );
        final longitudeParam = const fb.Float64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          16,
        );
        final zoomLevelParam = const fb.Int64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          18,
        );
        final object = GoMapInfo(
          id: idParam,
          name: nameParam,
          filePath: filePathParam,
          downloadUrl: downloadUrlParam,
          isTemporary: isTemporaryParam,
          latitude: latitudeParam,
          longitude: longitudeParam,
          zoomLevel: zoomLevelParam,
        );

        return object;
      },
    ),
    GoMinistry: obx_int.EntityDefinition<GoMinistry>(
      model: _entities[6],
      toOneRelations: (GoMinistry object) => [],
      toManyRelations: (GoMinistry object) => {
        obx_int.RelInfo<GoMinistry>.toMany(3, object.id): object.notes,
      },
      getId: (GoMinistry object) => object.id,
      setId: (GoMinistry object, int id) {
        object.id = id;
      },
      objectToFB: (GoMinistry object, fb.Builder fbb) {
        final ministryNameOffset = fbb.writeString(object.ministryName);
        final contactNameOffset = object.contactName == null
            ? null
            : fbb.writeString(object.contactName!);
        final addressOffset = object.address == null
            ? null
            : fbb.writeString(object.address!);
        final phoneOffset = object.phone == null
            ? null
            : fbb.writeString(object.phone!);
        final emailOffset = object.email == null
            ? null
            : fbb.writeString(object.email!);
        final partnerStatusOffset = object.partnerStatus == null
            ? null
            : fbb.writeString(object.partnerStatus!);
        fbb.startTable(10);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, ministryNameOffset);
        fbb.addOffset(2, contactNameOffset);
        fbb.addOffset(3, addressOffset);
        fbb.addOffset(4, phoneOffset);
        fbb.addOffset(5, emailOffset);
        fbb.addFloat64(6, object.latitude);
        fbb.addFloat64(7, object.longitude);
        fbb.addOffset(8, partnerStatusOffset);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final ministryNameParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final contactNameParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 8);
        final addressParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 10);
        final phoneParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 12);
        final emailParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 14);
        final latitudeParam = const fb.Float64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          16,
        );
        final longitudeParam = const fb.Float64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          18,
        );
        final partnerStatusParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 20);
        final object = GoMinistry(
          id: idParam,
          ministryName: ministryNameParam,
          contactName: contactNameParam,
          address: addressParam,
          phone: phoneParam,
          email: emailParam,
          latitude: latitudeParam,
          longitude: longitudeParam,
          partnerStatus: partnerStatusParam,
        );
        obx_int.InternalToManyAccess.setRelInfo<GoMinistry>(
          object.notes,
          store,
          obx_int.RelInfo<GoMinistry>.toMany(3, object.id),
        );
        return object;
      },
    ),
    GoMinistryNote: obx_int.EntityDefinition<GoMinistryNote>(
      model: _entities[7],
      toOneRelations: (GoMinistryNote object) => [object.ministry],
      toManyRelations: (GoMinistryNote object) => {},
      getId: (GoMinistryNote object) => object.id,
      setId: (GoMinistryNote object, int id) {
        object.id = id;
      },
      objectToFB: (GoMinistryNote object, fb.Builder fbb) {
        final contentOffset = fbb.writeString(object.content);
        fbb.startTable(6);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, contentOffset);
        fbb.addInt64(2, object.createdAt.millisecondsSinceEpoch);
        fbb.addInt64(3, object.updatedAt?.millisecondsSinceEpoch);
        fbb.addInt64(4, object.ministry.targetId);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final updatedAtValue = const fb.Int64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          10,
        );
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final contentParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final createdAtParam = DateTime.fromMillisecondsSinceEpoch(
          const fb.Int64Reader().vTableGet(buffer, rootOffset, 8, 0),
        );
        final updatedAtParam = updatedAtValue == null
            ? null
            : DateTime.fromMillisecondsSinceEpoch(updatedAtValue);
        final object = GoMinistryNote(
          id: idParam,
          content: contentParam,
          createdAt: createdAtParam,
          updatedAt: updatedAtParam,
        );
        object.ministry.targetId = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          12,
          0,
        );
        object.ministry.attach(store);
        return object;
      },
    ),
    GoStreet: obx_int.EntityDefinition<GoStreet>(
      model: _entities[8],
      toOneRelations: (GoStreet object) => [],
      toManyRelations: (GoStreet object) => {},
      getId: (GoStreet object) => object.id,
      setId: (GoStreet object, int id) {
        object.id = id;
      },
      objectToFB: (GoStreet object, fb.Builder fbb) {
        final nameOffset = fbb.writeString(object.name);
        final latitudesOffset = fbb.writeListFloat64(object.latitudes);
        final longitudesOffset = fbb.writeListFloat64(object.longitudes);
        final typeOffset = object.type == null
            ? null
            : fbb.writeString(object.type!);
        fbb.startTable(6);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, nameOffset);
        fbb.addOffset(2, latitudesOffset);
        fbb.addOffset(3, longitudesOffset);
        fbb.addOffset(4, typeOffset);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final nameParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final latitudesParam = const fb.ListReader<double>(
          fb.Float64Reader(),
          lazy: false,
        ).vTableGet(buffer, rootOffset, 8, []);
        final longitudesParam = const fb.ListReader<double>(
          fb.Float64Reader(),
          lazy: false,
        ).vTableGet(buffer, rootOffset, 10, []);
        final typeParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 12);
        final object = GoStreet(
          id: idParam,
          name: nameParam,
          latitudes: latitudesParam,
          longitudes: longitudesParam,
          type: typeParam,
        );

        return object;
      },
    ),
    GoZone: obx_int.EntityDefinition<GoZone>(
      model: _entities[9],
      toOneRelations: (GoZone object) => [],
      toManyRelations: (GoZone object) => {},
      getId: (GoZone object) => object.id,
      setId: (GoZone object, int id) {
        object.id = id;
      },
      objectToFB: (GoZone object, fb.Builder fbb) {
        final nameOffset = fbb.writeString(object.name);
        fbb.startTable(7);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, nameOffset);
        fbb.addFloat64(2, object.latitude);
        fbb.addFloat64(3, object.longitude);
        fbb.addFloat64(4, object.widthInMeters);
        fbb.addFloat64(5, object.heightInMeters);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final nameParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final latitudeParam = const fb.Float64Reader().vTableGet(
          buffer,
          rootOffset,
          8,
          0,
        );
        final longitudeParam = const fb.Float64Reader().vTableGet(
          buffer,
          rootOffset,
          10,
          0,
        );
        final widthInMetersParam = const fb.Float64Reader().vTableGet(
          buffer,
          rootOffset,
          12,
          0,
        );
        final heightInMetersParam = const fb.Float64Reader().vTableGet(
          buffer,
          rootOffset,
          14,
          0,
        );
        final object = GoZone(
          id: idParam,
          name: nameParam,
          latitude: latitudeParam,
          longitude: longitudeParam,
          widthInMeters: widthInMetersParam,
          heightInMeters: heightInMetersParam,
        );

        return object;
      },
    ),
    UserPreferences: obx_int.EntityDefinition<UserPreferences>(
      model: _entities[10],
      toOneRelations: (UserPreferences object) => [],
      toManyRelations: (UserPreferences object) => {},
      getId: (UserPreferences object) => object.id,
      setId: (UserPreferences object, int id) {
        object.id = id;
      },
      objectToFB: (UserPreferences object, fb.Builder fbb) {
        final currentMapOffset = object.currentMap == null
            ? null
            : fbb.writeString(object.currentMap!);
        final fontFamilyOffset = object.fontFamily == null
            ? null
            : fbb.writeString(object.fontFamily!);
        fbb.startTable(5);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, currentMapOffset);
        fbb.addOffset(2, fontFamilyOffset);
        fbb.addFloat64(3, object.fontSize);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final currentMapParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 6);
        final fontFamilyParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 8);
        final fontSizeParam = const fb.Float64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          10,
        );
        final object = UserPreferences(
          id: idParam,
          currentMap: currentMapParam,
          fontFamily: fontFamilyParam,
          fontSize: fontSizeParam,
        );

        return object;
      },
    ),
  };

  return obx_int.ModelDefinition(model, bindings);
}

/// [GoArea] entity fields to define ObjectBox queries.
class GoArea_ {
  /// See [GoArea.id].
  static final id = obx.QueryIntegerProperty<GoArea>(
    _entities[0].properties[0],
  );

  /// See [GoArea.name].
  static final name = obx.QueryStringProperty<GoArea>(
    _entities[0].properties[1],
  );

  /// See [GoArea.latitudes].
  static final latitudes = obx.QueryDoubleVectorProperty<GoArea>(
    _entities[0].properties[2],
  );

  /// See [GoArea.longitudes].
  static final longitudes = obx.QueryDoubleVectorProperty<GoArea>(
    _entities[0].properties[3],
  );
}

/// [GoChurch] entity fields to define ObjectBox queries.
class GoChurch_ {
  /// See [GoChurch.id].
  static final id = obx.QueryIntegerProperty<GoChurch>(
    _entities[1].properties[0],
  );

  /// See [GoChurch.churchName].
  static final churchName = obx.QueryStringProperty<GoChurch>(
    _entities[1].properties[1],
  );

  /// See [GoChurch.pastorName].
  static final pastorName = obx.QueryStringProperty<GoChurch>(
    _entities[1].properties[2],
  );

  /// See [GoChurch.address].
  static final address = obx.QueryStringProperty<GoChurch>(
    _entities[1].properties[3],
  );

  /// See [GoChurch.phone].
  static final phone = obx.QueryStringProperty<GoChurch>(
    _entities[1].properties[4],
  );

  /// See [GoChurch.email].
  static final email = obx.QueryStringProperty<GoChurch>(
    _entities[1].properties[5],
  );

  /// See [GoChurch.latitude].
  static final latitude = obx.QueryDoubleProperty<GoChurch>(
    _entities[1].properties[6],
  );

  /// See [GoChurch.longitude].
  static final longitude = obx.QueryDoubleProperty<GoChurch>(
    _entities[1].properties[7],
  );

  /// See [GoChurch.financialStatus].
  static final financialStatus = obx.QueryStringProperty<GoChurch>(
    _entities[1].properties[8],
  );

  /// see [GoChurch.notes]
  static final notes = obx.QueryRelationToMany<GoChurch, GoChurchNote>(
    _entities[1].relations[0],
  );
}

/// [GoChurchNote] entity fields to define ObjectBox queries.
class GoChurchNote_ {
  /// See [GoChurchNote.id].
  static final id = obx.QueryIntegerProperty<GoChurchNote>(
    _entities[2].properties[0],
  );

  /// See [GoChurchNote.content].
  static final content = obx.QueryStringProperty<GoChurchNote>(
    _entities[2].properties[1],
  );

  /// See [GoChurchNote.createdAt].
  static final createdAt = obx.QueryDateProperty<GoChurchNote>(
    _entities[2].properties[2],
  );

  /// See [GoChurchNote.updatedAt].
  static final updatedAt = obx.QueryDateProperty<GoChurchNote>(
    _entities[2].properties[3],
  );

  /// See [GoChurchNote.church].
  static final church = obx.QueryRelationToOne<GoChurchNote, GoChurch>(
    _entities[2].properties[4],
  );
}

/// [GoContact] entity fields to define ObjectBox queries.
class GoContact_ {
  /// See [GoContact.id].
  static final id = obx.QueryIntegerProperty<GoContact>(
    _entities[3].properties[0],
  );

  /// See [GoContact.fullName].
  static final fullName = obx.QueryStringProperty<GoContact>(
    _entities[3].properties[1],
  );

  /// See [GoContact.latitude].
  static final latitude = obx.QueryDoubleProperty<GoContact>(
    _entities[3].properties[2],
  );

  /// See [GoContact.longitude].
  static final longitude = obx.QueryDoubleProperty<GoContact>(
    _entities[3].properties[3],
  );

  /// See [GoContact.address].
  static final address = obx.QueryStringProperty<GoContact>(
    _entities[3].properties[4],
  );

  /// See [GoContact.birthday].
  static final birthday = obx.QueryStringProperty<GoContact>(
    _entities[3].properties[5],
  );

  /// See [GoContact.phone].
  static final phone = obx.QueryStringProperty<GoContact>(
    _entities[3].properties[6],
  );

  /// See [GoContact.email].
  static final email = obx.QueryStringProperty<GoContact>(
    _entities[3].properties[7],
  );

  /// See [GoContact.isVisited].
  static final isVisited = obx.QueryBooleanProperty<GoContact>(
    _entities[3].properties[8],
  );

  /// See [GoContact.eternalStatus].
  static final eternalStatus = obx.QueryStringProperty<GoContact>(
    _entities[3].properties[9],
  );

  /// see [GoContact.notes]
  static final notes = obx.QueryRelationToMany<GoContact, GoContactNote>(
    _entities[3].relations[0],
  );
}

/// [GoContactNote] entity fields to define ObjectBox queries.
class GoContactNote_ {
  /// See [GoContactNote.id].
  static final id = obx.QueryIntegerProperty<GoContactNote>(
    _entities[4].properties[0],
  );

  /// See [GoContactNote.content].
  static final content = obx.QueryStringProperty<GoContactNote>(
    _entities[4].properties[1],
  );

  /// See [GoContactNote.createdAt].
  static final createdAt = obx.QueryDateProperty<GoContactNote>(
    _entities[4].properties[2],
  );

  /// See [GoContactNote.updatedAt].
  static final updatedAt = obx.QueryDateProperty<GoContactNote>(
    _entities[4].properties[3],
  );

  /// See [GoContactNote.contact].
  static final contact = obx.QueryRelationToOne<GoContactNote, GoContact>(
    _entities[4].properties[4],
  );
}

/// [GoMapInfo] entity fields to define ObjectBox queries.
class GoMapInfo_ {
  /// See [GoMapInfo.id].
  static final id = obx.QueryIntegerProperty<GoMapInfo>(
    _entities[5].properties[0],
  );

  /// See [GoMapInfo.name].
  static final name = obx.QueryStringProperty<GoMapInfo>(
    _entities[5].properties[1],
  );

  /// See [GoMapInfo.filePath].
  static final filePath = obx.QueryStringProperty<GoMapInfo>(
    _entities[5].properties[2],
  );

  /// See [GoMapInfo.downloadUrl].
  static final downloadUrl = obx.QueryStringProperty<GoMapInfo>(
    _entities[5].properties[3],
  );

  /// See [GoMapInfo.isTemporary].
  static final isTemporary = obx.QueryBooleanProperty<GoMapInfo>(
    _entities[5].properties[4],
  );

  /// See [GoMapInfo.latitude].
  static final latitude = obx.QueryDoubleProperty<GoMapInfo>(
    _entities[5].properties[5],
  );

  /// See [GoMapInfo.longitude].
  static final longitude = obx.QueryDoubleProperty<GoMapInfo>(
    _entities[5].properties[6],
  );

  /// See [GoMapInfo.zoomLevel].
  static final zoomLevel = obx.QueryIntegerProperty<GoMapInfo>(
    _entities[5].properties[7],
  );
}

/// [GoMinistry] entity fields to define ObjectBox queries.
class GoMinistry_ {
  /// See [GoMinistry.id].
  static final id = obx.QueryIntegerProperty<GoMinistry>(
    _entities[6].properties[0],
  );

  /// See [GoMinistry.ministryName].
  static final ministryName = obx.QueryStringProperty<GoMinistry>(
    _entities[6].properties[1],
  );

  /// See [GoMinistry.contactName].
  static final contactName = obx.QueryStringProperty<GoMinistry>(
    _entities[6].properties[2],
  );

  /// See [GoMinistry.address].
  static final address = obx.QueryStringProperty<GoMinistry>(
    _entities[6].properties[3],
  );

  /// See [GoMinistry.phone].
  static final phone = obx.QueryStringProperty<GoMinistry>(
    _entities[6].properties[4],
  );

  /// See [GoMinistry.email].
  static final email = obx.QueryStringProperty<GoMinistry>(
    _entities[6].properties[5],
  );

  /// See [GoMinistry.latitude].
  static final latitude = obx.QueryDoubleProperty<GoMinistry>(
    _entities[6].properties[6],
  );

  /// See [GoMinistry.longitude].
  static final longitude = obx.QueryDoubleProperty<GoMinistry>(
    _entities[6].properties[7],
  );

  /// See [GoMinistry.partnerStatus].
  static final partnerStatus = obx.QueryStringProperty<GoMinistry>(
    _entities[6].properties[8],
  );

  /// see [GoMinistry.notes]
  static final notes = obx.QueryRelationToMany<GoMinistry, GoMinistryNote>(
    _entities[6].relations[0],
  );
}

/// [GoMinistryNote] entity fields to define ObjectBox queries.
class GoMinistryNote_ {
  /// See [GoMinistryNote.id].
  static final id = obx.QueryIntegerProperty<GoMinistryNote>(
    _entities[7].properties[0],
  );

  /// See [GoMinistryNote.content].
  static final content = obx.QueryStringProperty<GoMinistryNote>(
    _entities[7].properties[1],
  );

  /// See [GoMinistryNote.createdAt].
  static final createdAt = obx.QueryDateProperty<GoMinistryNote>(
    _entities[7].properties[2],
  );

  /// See [GoMinistryNote.updatedAt].
  static final updatedAt = obx.QueryDateProperty<GoMinistryNote>(
    _entities[7].properties[3],
  );

  /// See [GoMinistryNote.ministry].
  static final ministry = obx.QueryRelationToOne<GoMinistryNote, GoMinistry>(
    _entities[7].properties[4],
  );
}

/// [GoStreet] entity fields to define ObjectBox queries.
class GoStreet_ {
  /// See [GoStreet.id].
  static final id = obx.QueryIntegerProperty<GoStreet>(
    _entities[8].properties[0],
  );

  /// See [GoStreet.name].
  static final name = obx.QueryStringProperty<GoStreet>(
    _entities[8].properties[1],
  );

  /// See [GoStreet.latitudes].
  static final latitudes = obx.QueryDoubleVectorProperty<GoStreet>(
    _entities[8].properties[2],
  );

  /// See [GoStreet.longitudes].
  static final longitudes = obx.QueryDoubleVectorProperty<GoStreet>(
    _entities[8].properties[3],
  );

  /// See [GoStreet.type].
  static final type = obx.QueryStringProperty<GoStreet>(
    _entities[8].properties[4],
  );
}

/// [GoZone] entity fields to define ObjectBox queries.
class GoZone_ {
  /// See [GoZone.id].
  static final id = obx.QueryIntegerProperty<GoZone>(
    _entities[9].properties[0],
  );

  /// See [GoZone.name].
  static final name = obx.QueryStringProperty<GoZone>(
    _entities[9].properties[1],
  );

  /// See [GoZone.latitude].
  static final latitude = obx.QueryDoubleProperty<GoZone>(
    _entities[9].properties[2],
  );

  /// See [GoZone.longitude].
  static final longitude = obx.QueryDoubleProperty<GoZone>(
    _entities[9].properties[3],
  );

  /// See [GoZone.widthInMeters].
  static final widthInMeters = obx.QueryDoubleProperty<GoZone>(
    _entities[9].properties[4],
  );

  /// See [GoZone.heightInMeters].
  static final heightInMeters = obx.QueryDoubleProperty<GoZone>(
    _entities[9].properties[5],
  );
}

/// [UserPreferences] entity fields to define ObjectBox queries.
class UserPreferences_ {
  /// See [UserPreferences.id].
  static final id = obx.QueryIntegerProperty<UserPreferences>(
    _entities[10].properties[0],
  );

  /// See [UserPreferences.currentMap].
  static final currentMap = obx.QueryStringProperty<UserPreferences>(
    _entities[10].properties[1],
  );

  /// See [UserPreferences.fontFamily].
  static final fontFamily = obx.QueryStringProperty<UserPreferences>(
    _entities[10].properties[2],
  );

  /// See [UserPreferences.fontSize].
  static final fontSize = obx.QueryDoubleProperty<UserPreferences>(
    _entities[10].properties[3],
  );
}
