// GENERATED CODE - DO NOT MODIFY BY HAND
// This code was generated by ObjectBox. To update it run the generator again
// with `dart run build_runner build`.
// See also https://docs.objectbox.io/getting-started#generate-objectbox-code

// ignore_for_file: camel_case_types, depend_on_referenced_packages
// coverage:ignore-file

import 'dart:typed_data';

import 'package:flat_buffers/flat_buffers.dart' as fb;
import 'package:objectbox/internal.dart'
    as obx_int; // generated code can access "internal" functionality
import 'package:objectbox/objectbox.dart' as obx;
import 'package:objectbox_flutter_libs/objectbox_flutter_libs.dart';

import 'core/models/user_preferences_model.dart';
import 'features/go/models/go_map_info_model.dart';
import 'features/go/models/go_model.dart';
import 'features/go/models/go_route_models.dart';

export 'package:objectbox/objectbox.dart'; // so that callers only have to import this file

final _entities = <obx_int.ModelEntity>[
  obx_int.ModelEntity(
    id: const obx_int.IdUid(1, 5582790263466527757),
    name: 'GoArea',
    lastPropertyId: const obx_int.IdUid(4, 9178513491962404501),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 7235984030353438707),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 7532918629000764498),
        name: 'name',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 2192183835355609921),
        name: 'latitudes',
        type: 29,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 9178513491962404501),
        name: 'longitudes',
        type: 29,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(2, 617274417850421234),
    name: 'GoChurch',
    lastPropertyId: const obx_int.IdUid(10, 6591777561456935950),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 8146868463476559606),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 5490693575485499683),
        name: 'churchName',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 5311760643605323066),
        name: 'pastorName',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 5415506636064160596),
        name: 'address',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 3671821654040521139),
        name: 'phone',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 7461468676268513019),
        name: 'email',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 8668432398019807928),
        name: 'latitude',
        type: 8,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(8, 8479346151156513137),
        name: 'longitude',
        type: 8,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(9, 7322173543935159606),
        name: 'notes',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(10, 6591777561456935950),
        name: 'financialStatus',
        type: 9,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(3, 4843402951861643435),
    name: 'GoContact',
    lastPropertyId: const obx_int.IdUid(11, 4209067528519757785),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 7150753814689449775),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 3272004208726430981),
        name: 'fullName',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 8368226633113180446),
        name: 'latitude',
        type: 8,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 2732301827629013660),
        name: 'longitude',
        type: 8,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 1316683080771179697),
        name: 'address',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 1338017715721463943),
        name: 'birthday',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 9082662134181367465),
        name: 'phone',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(8, 8371905711976189197),
        name: 'email',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(9, 2519045439322071478),
        name: 'notes',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(10, 5325670356115944680),
        name: 'isVisited',
        type: 1,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(11, 4209067528519757785),
        name: 'eternalStatus',
        type: 9,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(4, 5266182212854202202),
    name: 'GoMapInfo',
    lastPropertyId: const obx_int.IdUid(8, 395058414019089862),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 1477816354764043396),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 8218689587253829208),
        name: 'name',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 9181346021258935363),
        name: 'filePath',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 5767360522583140112),
        name: 'downloadUrl',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 7728279994918884328),
        name: 'isTemporary',
        type: 1,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 3160802649745173229),
        name: 'latitude',
        type: 8,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 6978180725063933854),
        name: 'longitude',
        type: 8,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(8, 395058414019089862),
        name: 'zoomLevel',
        type: 6,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(5, 5113859085895848472),
    name: 'GoMinistry',
    lastPropertyId: const obx_int.IdUid(10, 6249470426540289428),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 8842680554983056591),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 9047563894245238859),
        name: 'ministryName',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 4387866823571959985),
        name: 'contactName',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 1066546884878142958),
        name: 'address',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 1873355117026701689),
        name: 'phone',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 4554576249394651908),
        name: 'email',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 6910834249777067595),
        name: 'latitude',
        type: 8,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(8, 4105354923001845036),
        name: 'longitude',
        type: 8,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(9, 6019555721538886696),
        name: 'notes',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(10, 6249470426540289428),
        name: 'partnerStatus',
        type: 9,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(6, 5340594820126555634),
    name: 'GoStreet',
    lastPropertyId: const obx_int.IdUid(4, 8962038482108900063),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 2068305710822281230),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 7350840351179095653),
        name: 'name',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 9144362673188020143),
        name: 'latitudes',
        type: 29,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 8962038482108900063),
        name: 'longitudes',
        type: 29,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(7, 6757020593258638379),
    name: 'GoZone',
    lastPropertyId: const obx_int.IdUid(6, 1575999583038434192),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 4309760863366084940),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 8020534629253955665),
        name: 'name',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 6764777498343026223),
        name: 'latitude',
        type: 8,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 7617206223964687019),
        name: 'longitude',
        type: 8,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 923474122931027754),
        name: 'widthInMeters',
        type: 8,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 1575999583038434192),
        name: 'heightInMeters',
        type: 8,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(8, 3414335988801914007),
    name: 'UserPreferences',
    lastPropertyId: const obx_int.IdUid(4, 2978440734427674223),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 1509567843873613465),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 2559777702520172257),
        name: 'currentMap',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 5033305490852918278),
        name: 'fontFamily',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 2978440734427674223),
        name: 'fontSize',
        type: 8,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
];

/// Shortcut for [obx.Store.new] that passes [getObjectBoxModel] and for Flutter
/// apps by default a [directory] using `defaultStoreDirectory()` from the
/// ObjectBox Flutter library.
///
/// Note: for desktop apps it is recommended to specify a unique [directory].
///
/// See [obx.Store.new] for an explanation of all parameters.
///
/// For Flutter apps, also calls `loadObjectBoxLibraryAndroidCompat()` from
/// the ObjectBox Flutter library to fix loading the native ObjectBox library
/// on Android 6 and older.
Future<obx.Store> openStore({
  String? directory,
  int? maxDBSizeInKB,
  int? maxDataSizeInKB,
  int? fileMode,
  int? maxReaders,
  bool queriesCaseSensitiveDefault = true,
  String? macosApplicationGroup,
}) async {
  await loadObjectBoxLibraryAndroidCompat();
  return obx.Store(
    getObjectBoxModel(),
    directory: directory ?? (await defaultStoreDirectory()).path,
    maxDBSizeInKB: maxDBSizeInKB,
    maxDataSizeInKB: maxDataSizeInKB,
    fileMode: fileMode,
    maxReaders: maxReaders,
    queriesCaseSensitiveDefault: queriesCaseSensitiveDefault,
    macosApplicationGroup: macosApplicationGroup,
  );
}

/// Returns the ObjectBox model definition for this project for use with
/// [obx.Store.new].
obx_int.ModelDefinition getObjectBoxModel() {
  final model = obx_int.ModelInfo(
    entities: _entities,
    lastEntityId: const obx_int.IdUid(8, 3414335988801914007),
    lastIndexId: const obx_int.IdUid(0, 0),
    lastRelationId: const obx_int.IdUid(0, 0),
    lastSequenceId: const obx_int.IdUid(0, 0),
    retiredEntityUids: const [],
    retiredIndexUids: const [],
    retiredPropertyUids: const [],
    retiredRelationUids: const [],
    modelVersion: 5,
    modelVersionParserMinimum: 5,
    version: 1,
  );

  final bindings = <Type, obx_int.EntityDefinition>{
    GoArea: obx_int.EntityDefinition<GoArea>(
      model: _entities[0],
      toOneRelations: (GoArea object) => [],
      toManyRelations: (GoArea object) => {},
      getId: (GoArea object) => object.id,
      setId: (GoArea object, int id) {
        object.id = id;
      },
      objectToFB: (GoArea object, fb.Builder fbb) {
        final nameOffset = fbb.writeString(object.name);
        final latitudesOffset = fbb.writeListFloat64(object.latitudes);
        final longitudesOffset = fbb.writeListFloat64(object.longitudes);
        fbb.startTable(5);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, nameOffset);
        fbb.addOffset(2, latitudesOffset);
        fbb.addOffset(3, longitudesOffset);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final nameParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final latitudesParam = const fb.ListReader<double>(
          fb.Float64Reader(),
          lazy: false,
        ).vTableGet(buffer, rootOffset, 8, []);
        final longitudesParam = const fb.ListReader<double>(
          fb.Float64Reader(),
          lazy: false,
        ).vTableGet(buffer, rootOffset, 10, []);
        final object = GoArea(
          id: idParam,
          name: nameParam,
          latitudes: latitudesParam,
          longitudes: longitudesParam,
        );

        return object;
      },
    ),
    GoChurch: obx_int.EntityDefinition<GoChurch>(
      model: _entities[1],
      toOneRelations: (GoChurch object) => [],
      toManyRelations: (GoChurch object) => {},
      getId: (GoChurch object) => object.id,
      setId: (GoChurch object, int id) {
        object.id = id;
      },
      objectToFB: (GoChurch object, fb.Builder fbb) {
        final churchNameOffset = fbb.writeString(object.churchName);
        final pastorNameOffset = object.pastorName == null
            ? null
            : fbb.writeString(object.pastorName!);
        final addressOffset = object.address == null
            ? null
            : fbb.writeString(object.address!);
        final phoneOffset = object.phone == null
            ? null
            : fbb.writeString(object.phone!);
        final emailOffset = object.email == null
            ? null
            : fbb.writeString(object.email!);
        final notesOffset = object.notes == null
            ? null
            : fbb.writeString(object.notes!);
        final financialStatusOffset = object.financialStatus == null
            ? null
            : fbb.writeString(object.financialStatus!);
        fbb.startTable(11);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, churchNameOffset);
        fbb.addOffset(2, pastorNameOffset);
        fbb.addOffset(3, addressOffset);
        fbb.addOffset(4, phoneOffset);
        fbb.addOffset(5, emailOffset);
        fbb.addFloat64(6, object.latitude);
        fbb.addFloat64(7, object.longitude);
        fbb.addOffset(8, notesOffset);
        fbb.addOffset(9, financialStatusOffset);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final churchNameParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final pastorNameParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 8);
        final addressParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 10);
        final phoneParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 12);
        final emailParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 14);
        final latitudeParam = const fb.Float64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          16,
        );
        final longitudeParam = const fb.Float64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          18,
        );
        final notesParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 20);
        final financialStatusParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 22);
        final object = GoChurch(
          id: idParam,
          churchName: churchNameParam,
          pastorName: pastorNameParam,
          address: addressParam,
          phone: phoneParam,
          email: emailParam,
          latitude: latitudeParam,
          longitude: longitudeParam,
          notes: notesParam,
          financialStatus: financialStatusParam,
        );

        return object;
      },
    ),
    GoContact: obx_int.EntityDefinition<GoContact>(
      model: _entities[2],
      toOneRelations: (GoContact object) => [],
      toManyRelations: (GoContact object) => {},
      getId: (GoContact object) => object.id,
      setId: (GoContact object, int id) {
        object.id = id;
      },
      objectToFB: (GoContact object, fb.Builder fbb) {
        final fullNameOffset = fbb.writeString(object.fullName);
        final addressOffset = object.address == null
            ? null
            : fbb.writeString(object.address!);
        final birthdayOffset = object.birthday == null
            ? null
            : fbb.writeString(object.birthday!);
        final phoneOffset = object.phone == null
            ? null
            : fbb.writeString(object.phone!);
        final emailOffset = object.email == null
            ? null
            : fbb.writeString(object.email!);
        final notesOffset = object.notes == null
            ? null
            : fbb.writeString(object.notes!);
        final eternalStatusOffset = object.eternalStatus == null
            ? null
            : fbb.writeString(object.eternalStatus!);
        fbb.startTable(12);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, fullNameOffset);
        fbb.addFloat64(2, object.latitude);
        fbb.addFloat64(3, object.longitude);
        fbb.addOffset(4, addressOffset);
        fbb.addOffset(5, birthdayOffset);
        fbb.addOffset(6, phoneOffset);
        fbb.addOffset(7, emailOffset);
        fbb.addOffset(8, notesOffset);
        fbb.addBool(9, object.isVisited);
        fbb.addOffset(10, eternalStatusOffset);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final fullNameParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final latitudeParam = const fb.Float64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          8,
        );
        final longitudeParam = const fb.Float64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          10,
        );
        final addressParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 12);
        final birthdayParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 14);
        final phoneParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 16);
        final emailParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 18);
        final notesParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 20);
        final isVisitedParam = const fb.BoolReader().vTableGet(
          buffer,
          rootOffset,
          22,
          false,
        );
        final eternalStatusParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 24);
        final object = GoContact(
          id: idParam,
          fullName: fullNameParam,
          latitude: latitudeParam,
          longitude: longitudeParam,
          address: addressParam,
          birthday: birthdayParam,
          phone: phoneParam,
          email: emailParam,
          notes: notesParam,
          isVisited: isVisitedParam,
          eternalStatus: eternalStatusParam,
        );

        return object;
      },
    ),
    GoMapInfo: obx_int.EntityDefinition<GoMapInfo>(
      model: _entities[3],
      toOneRelations: (GoMapInfo object) => [],
      toManyRelations: (GoMapInfo object) => {},
      getId: (GoMapInfo object) => object.id,
      setId: (GoMapInfo object, int id) {
        object.id = id;
      },
      objectToFB: (GoMapInfo object, fb.Builder fbb) {
        final nameOffset = fbb.writeString(object.name);
        final filePathOffset = object.filePath == null
            ? null
            : fbb.writeString(object.filePath!);
        final downloadUrlOffset = object.downloadUrl == null
            ? null
            : fbb.writeString(object.downloadUrl!);
        fbb.startTable(9);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, nameOffset);
        fbb.addOffset(2, filePathOffset);
        fbb.addOffset(3, downloadUrlOffset);
        fbb.addBool(4, object.isTemporary);
        fbb.addFloat64(5, object.latitude);
        fbb.addFloat64(6, object.longitude);
        fbb.addInt64(7, object.zoomLevel);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final nameParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final filePathParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 8);
        final downloadUrlParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 10);
        final isTemporaryParam = const fb.BoolReader().vTableGetNullable(
          buffer,
          rootOffset,
          12,
        );
        final latitudeParam = const fb.Float64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          14,
        );
        final longitudeParam = const fb.Float64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          16,
        );
        final zoomLevelParam = const fb.Int64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          18,
        );
        final object = GoMapInfo(
          id: idParam,
          name: nameParam,
          filePath: filePathParam,
          downloadUrl: downloadUrlParam,
          isTemporary: isTemporaryParam,
          latitude: latitudeParam,
          longitude: longitudeParam,
          zoomLevel: zoomLevelParam,
        );

        return object;
      },
    ),
    GoMinistry: obx_int.EntityDefinition<GoMinistry>(
      model: _entities[4],
      toOneRelations: (GoMinistry object) => [],
      toManyRelations: (GoMinistry object) => {},
      getId: (GoMinistry object) => object.id,
      setId: (GoMinistry object, int id) {
        object.id = id;
      },
      objectToFB: (GoMinistry object, fb.Builder fbb) {
        final ministryNameOffset = fbb.writeString(object.ministryName);
        final contactNameOffset = object.contactName == null
            ? null
            : fbb.writeString(object.contactName!);
        final addressOffset = object.address == null
            ? null
            : fbb.writeString(object.address!);
        final phoneOffset = object.phone == null
            ? null
            : fbb.writeString(object.phone!);
        final emailOffset = object.email == null
            ? null
            : fbb.writeString(object.email!);
        final notesOffset = object.notes == null
            ? null
            : fbb.writeString(object.notes!);
        final partnerStatusOffset = object.partnerStatus == null
            ? null
            : fbb.writeString(object.partnerStatus!);
        fbb.startTable(11);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, ministryNameOffset);
        fbb.addOffset(2, contactNameOffset);
        fbb.addOffset(3, addressOffset);
        fbb.addOffset(4, phoneOffset);
        fbb.addOffset(5, emailOffset);
        fbb.addFloat64(6, object.latitude);
        fbb.addFloat64(7, object.longitude);
        fbb.addOffset(8, notesOffset);
        fbb.addOffset(9, partnerStatusOffset);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final ministryNameParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final contactNameParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 8);
        final addressParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 10);
        final phoneParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 12);
        final emailParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 14);
        final latitudeParam = const fb.Float64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          16,
        );
        final longitudeParam = const fb.Float64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          18,
        );
        final notesParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 20);
        final partnerStatusParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 22);
        final object = GoMinistry(
          id: idParam,
          ministryName: ministryNameParam,
          contactName: contactNameParam,
          address: addressParam,
          phone: phoneParam,
          email: emailParam,
          latitude: latitudeParam,
          longitude: longitudeParam,
          notes: notesParam,
          partnerStatus: partnerStatusParam,
        );

        return object;
      },
    ),
    GoStreet: obx_int.EntityDefinition<GoStreet>(
      model: _entities[5],
      toOneRelations: (GoStreet object) => [],
      toManyRelations: (GoStreet object) => {},
      getId: (GoStreet object) => object.id,
      setId: (GoStreet object, int id) {
        object.id = id;
      },
      objectToFB: (GoStreet object, fb.Builder fbb) {
        final nameOffset = fbb.writeString(object.name);
        final latitudesOffset = fbb.writeListFloat64(object.latitudes);
        final longitudesOffset = fbb.writeListFloat64(object.longitudes);
        fbb.startTable(5);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, nameOffset);
        fbb.addOffset(2, latitudesOffset);
        fbb.addOffset(3, longitudesOffset);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final nameParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final latitudesParam = const fb.ListReader<double>(
          fb.Float64Reader(),
          lazy: false,
        ).vTableGet(buffer, rootOffset, 8, []);
        final longitudesParam = const fb.ListReader<double>(
          fb.Float64Reader(),
          lazy: false,
        ).vTableGet(buffer, rootOffset, 10, []);
        final object = GoStreet(
          id: idParam,
          name: nameParam,
          latitudes: latitudesParam,
          longitudes: longitudesParam,
        );

        return object;
      },
    ),
    GoZone: obx_int.EntityDefinition<GoZone>(
      model: _entities[6],
      toOneRelations: (GoZone object) => [],
      toManyRelations: (GoZone object) => {},
      getId: (GoZone object) => object.id,
      setId: (GoZone object, int id) {
        object.id = id;
      },
      objectToFB: (GoZone object, fb.Builder fbb) {
        final nameOffset = fbb.writeString(object.name);
        fbb.startTable(7);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, nameOffset);
        fbb.addFloat64(2, object.latitude);
        fbb.addFloat64(3, object.longitude);
        fbb.addFloat64(4, object.widthInMeters);
        fbb.addFloat64(5, object.heightInMeters);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final nameParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final latitudeParam = const fb.Float64Reader().vTableGet(
          buffer,
          rootOffset,
          8,
          0,
        );
        final longitudeParam = const fb.Float64Reader().vTableGet(
          buffer,
          rootOffset,
          10,
          0,
        );
        final widthInMetersParam = const fb.Float64Reader().vTableGet(
          buffer,
          rootOffset,
          12,
          0,
        );
        final heightInMetersParam = const fb.Float64Reader().vTableGet(
          buffer,
          rootOffset,
          14,
          0,
        );
        final object = GoZone(
          name: nameParam,
          latitude: latitudeParam,
          longitude: longitudeParam,
          widthInMeters: widthInMetersParam,
          heightInMeters: heightInMetersParam,
        )..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);

        return object;
      },
    ),
    UserPreferences: obx_int.EntityDefinition<UserPreferences>(
      model: _entities[7],
      toOneRelations: (UserPreferences object) => [],
      toManyRelations: (UserPreferences object) => {},
      getId: (UserPreferences object) => object.id,
      setId: (UserPreferences object, int id) {
        object.id = id;
      },
      objectToFB: (UserPreferences object, fb.Builder fbb) {
        final currentMapOffset = object.currentMap == null
            ? null
            : fbb.writeString(object.currentMap!);
        final fontFamilyOffset = object.fontFamily == null
            ? null
            : fbb.writeString(object.fontFamily!);
        fbb.startTable(5);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, currentMapOffset);
        fbb.addOffset(2, fontFamilyOffset);
        fbb.addFloat64(3, object.fontSize);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final currentMapParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 6);
        final fontFamilyParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 8);
        final fontSizeParam = const fb.Float64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          10,
        );
        final object = UserPreferences(
          id: idParam,
          currentMap: currentMapParam,
          fontFamily: fontFamilyParam,
          fontSize: fontSizeParam,
        );

        return object;
      },
    ),
  };

  return obx_int.ModelDefinition(model, bindings);
}

/// [GoArea] entity fields to define ObjectBox queries.
class GoArea_ {
  /// See [GoArea.id].
  static final id = obx.QueryIntegerProperty<GoArea>(
    _entities[0].properties[0],
  );

  /// See [GoArea.name].
  static final name = obx.QueryStringProperty<GoArea>(
    _entities[0].properties[1],
  );

  /// See [GoArea.latitudes].
  static final latitudes = obx.QueryDoubleVectorProperty<GoArea>(
    _entities[0].properties[2],
  );

  /// See [GoArea.longitudes].
  static final longitudes = obx.QueryDoubleVectorProperty<GoArea>(
    _entities[0].properties[3],
  );
}

/// [GoChurch] entity fields to define ObjectBox queries.
class GoChurch_ {
  /// See [GoChurch.id].
  static final id = obx.QueryIntegerProperty<GoChurch>(
    _entities[1].properties[0],
  );

  /// See [GoChurch.churchName].
  static final churchName = obx.QueryStringProperty<GoChurch>(
    _entities[1].properties[1],
  );

  /// See [GoChurch.pastorName].
  static final pastorName = obx.QueryStringProperty<GoChurch>(
    _entities[1].properties[2],
  );

  /// See [GoChurch.address].
  static final address = obx.QueryStringProperty<GoChurch>(
    _entities[1].properties[3],
  );

  /// See [GoChurch.phone].
  static final phone = obx.QueryStringProperty<GoChurch>(
    _entities[1].properties[4],
  );

  /// See [GoChurch.email].
  static final email = obx.QueryStringProperty<GoChurch>(
    _entities[1].properties[5],
  );

  /// See [GoChurch.latitude].
  static final latitude = obx.QueryDoubleProperty<GoChurch>(
    _entities[1].properties[6],
  );

  /// See [GoChurch.longitude].
  static final longitude = obx.QueryDoubleProperty<GoChurch>(
    _entities[1].properties[7],
  );

  /// See [GoChurch.notes].
  static final notes = obx.QueryStringProperty<GoChurch>(
    _entities[1].properties[8],
  );

  /// See [GoChurch.financialStatus].
  static final financialStatus = obx.QueryStringProperty<GoChurch>(
    _entities[1].properties[9],
  );
}

/// [GoContact] entity fields to define ObjectBox queries.
class GoContact_ {
  /// See [GoContact.id].
  static final id = obx.QueryIntegerProperty<GoContact>(
    _entities[2].properties[0],
  );

  /// See [GoContact.fullName].
  static final fullName = obx.QueryStringProperty<GoContact>(
    _entities[2].properties[1],
  );

  /// See [GoContact.latitude].
  static final latitude = obx.QueryDoubleProperty<GoContact>(
    _entities[2].properties[2],
  );

  /// See [GoContact.longitude].
  static final longitude = obx.QueryDoubleProperty<GoContact>(
    _entities[2].properties[3],
  );

  /// See [GoContact.address].
  static final address = obx.QueryStringProperty<GoContact>(
    _entities[2].properties[4],
  );

  /// See [GoContact.birthday].
  static final birthday = obx.QueryStringProperty<GoContact>(
    _entities[2].properties[5],
  );

  /// See [GoContact.phone].
  static final phone = obx.QueryStringProperty<GoContact>(
    _entities[2].properties[6],
  );

  /// See [GoContact.email].
  static final email = obx.QueryStringProperty<GoContact>(
    _entities[2].properties[7],
  );

  /// See [GoContact.notes].
  static final notes = obx.QueryStringProperty<GoContact>(
    _entities[2].properties[8],
  );

  /// See [GoContact.isVisited].
  static final isVisited = obx.QueryBooleanProperty<GoContact>(
    _entities[2].properties[9],
  );

  /// See [GoContact.eternalStatus].
  static final eternalStatus = obx.QueryStringProperty<GoContact>(
    _entities[2].properties[10],
  );
}

/// [GoMapInfo] entity fields to define ObjectBox queries.
class GoMapInfo_ {
  /// See [GoMapInfo.id].
  static final id = obx.QueryIntegerProperty<GoMapInfo>(
    _entities[3].properties[0],
  );

  /// See [GoMapInfo.name].
  static final name = obx.QueryStringProperty<GoMapInfo>(
    _entities[3].properties[1],
  );

  /// See [GoMapInfo.filePath].
  static final filePath = obx.QueryStringProperty<GoMapInfo>(
    _entities[3].properties[2],
  );

  /// See [GoMapInfo.downloadUrl].
  static final downloadUrl = obx.QueryStringProperty<GoMapInfo>(
    _entities[3].properties[3],
  );

  /// See [GoMapInfo.isTemporary].
  static final isTemporary = obx.QueryBooleanProperty<GoMapInfo>(
    _entities[3].properties[4],
  );

  /// See [GoMapInfo.latitude].
  static final latitude = obx.QueryDoubleProperty<GoMapInfo>(
    _entities[3].properties[5],
  );

  /// See [GoMapInfo.longitude].
  static final longitude = obx.QueryDoubleProperty<GoMapInfo>(
    _entities[3].properties[6],
  );

  /// See [GoMapInfo.zoomLevel].
  static final zoomLevel = obx.QueryIntegerProperty<GoMapInfo>(
    _entities[3].properties[7],
  );
}

/// [GoMinistry] entity fields to define ObjectBox queries.
class GoMinistry_ {
  /// See [GoMinistry.id].
  static final id = obx.QueryIntegerProperty<GoMinistry>(
    _entities[4].properties[0],
  );

  /// See [GoMinistry.ministryName].
  static final ministryName = obx.QueryStringProperty<GoMinistry>(
    _entities[4].properties[1],
  );

  /// See [GoMinistry.contactName].
  static final contactName = obx.QueryStringProperty<GoMinistry>(
    _entities[4].properties[2],
  );

  /// See [GoMinistry.address].
  static final address = obx.QueryStringProperty<GoMinistry>(
    _entities[4].properties[3],
  );

  /// See [GoMinistry.phone].
  static final phone = obx.QueryStringProperty<GoMinistry>(
    _entities[4].properties[4],
  );

  /// See [GoMinistry.email].
  static final email = obx.QueryStringProperty<GoMinistry>(
    _entities[4].properties[5],
  );

  /// See [GoMinistry.latitude].
  static final latitude = obx.QueryDoubleProperty<GoMinistry>(
    _entities[4].properties[6],
  );

  /// See [GoMinistry.longitude].
  static final longitude = obx.QueryDoubleProperty<GoMinistry>(
    _entities[4].properties[7],
  );

  /// See [GoMinistry.notes].
  static final notes = obx.QueryStringProperty<GoMinistry>(
    _entities[4].properties[8],
  );

  /// See [GoMinistry.partnerStatus].
  static final partnerStatus = obx.QueryStringProperty<GoMinistry>(
    _entities[4].properties[9],
  );
}

/// [GoStreet] entity fields to define ObjectBox queries.
class GoStreet_ {
  /// See [GoStreet.id].
  static final id = obx.QueryIntegerProperty<GoStreet>(
    _entities[5].properties[0],
  );

  /// See [GoStreet.name].
  static final name = obx.QueryStringProperty<GoStreet>(
    _entities[5].properties[1],
  );

  /// See [GoStreet.latitudes].
  static final latitudes = obx.QueryDoubleVectorProperty<GoStreet>(
    _entities[5].properties[2],
  );

  /// See [GoStreet.longitudes].
  static final longitudes = obx.QueryDoubleVectorProperty<GoStreet>(
    _entities[5].properties[3],
  );
}

/// [GoZone] entity fields to define ObjectBox queries.
class GoZone_ {
  /// See [GoZone.id].
  static final id = obx.QueryIntegerProperty<GoZone>(
    _entities[6].properties[0],
  );

  /// See [GoZone.name].
  static final name = obx.QueryStringProperty<GoZone>(
    _entities[6].properties[1],
  );

  /// See [GoZone.latitude].
  static final latitude = obx.QueryDoubleProperty<GoZone>(
    _entities[6].properties[2],
  );

  /// See [GoZone.longitude].
  static final longitude = obx.QueryDoubleProperty<GoZone>(
    _entities[6].properties[3],
  );

  /// See [GoZone.widthInMeters].
  static final widthInMeters = obx.QueryDoubleProperty<GoZone>(
    _entities[6].properties[4],
  );

  /// See [GoZone.heightInMeters].
  static final heightInMeters = obx.QueryDoubleProperty<GoZone>(
    _entities[6].properties[5],
  );
}

/// [UserPreferences] entity fields to define ObjectBox queries.
class UserPreferences_ {
  /// See [UserPreferences.id].
  static final id = obx.QueryIntegerProperty<UserPreferences>(
    _entities[7].properties[0],
  );

  /// See [UserPreferences.currentMap].
  static final currentMap = obx.QueryStringProperty<UserPreferences>(
    _entities[7].properties[1],
  );

  /// See [UserPreferences.fontFamily].
  static final fontFamily = obx.QueryStringProperty<UserPreferences>(
    _entities[7].properties[2],
  );

  /// See [UserPreferences.fontSize].
  static final fontSize = obx.QueryDoubleProperty<UserPreferences>(
    _entities[7].properties[3],
  );
}
