// GENERATED CODE - DO NOT MODIFY BY HAND
// This code was generated by ObjectBox. To update it run the generator again
// with `dart run build_runner build`.
// See also https://docs.objectbox.io/getting-started#generate-objectbox-code

// ignore_for_file: camel_case_types, depend_on_referenced_packages
// coverage:ignore-file

import 'dart:typed_data';

import 'package:flat_buffers/flat_buffers.dart' as fb;
import 'package:objectbox/internal.dart'
    as obx_int; // generated code can access "internal" functionality
import 'package:objectbox/objectbox.dart' as obx;
import 'package:objectbox_flutter_libs/objectbox_flutter_libs.dart';

import 'core/models/user_preferences_model.dart';
import 'features/go/models/go_map_info_model.dart';
import 'features/go/models/go_model.dart';
import 'features/go/models/go_route_models.dart';
import 'features/home/models/home_model.dart';
import 'features/study/models/study_bibles_model.dart';
import 'features/study/models/study_references_model.dart';
import 'features/study/models/study_topics_model.dart';

export 'package:objectbox/objectbox.dart'; // so that callers only have to import this file

final _entities = <obx_int.ModelEntity>[
  obx_int.ModelEntity(
    id: const obx_int.IdUid(1, 8876859298030233747),
    name: 'BibleVersion',
    lastPropertyId: const obx_int.IdUid(3, 7792399591903646773),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 9120296464622157694),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 1503201243541822074),
        name: 'name',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 7792399591903646773),
        name: 'languageCode',
        type: 9,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[
      obx_int.ModelBacklink(name: 'books', srcEntity: 'Book', srcField: ''),
    ],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(2, 6740698237279462509),
    name: 'BiblesDownload',
    lastPropertyId: const obx_int.IdUid(4, 1823838358828141343),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 1976378965074149723),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 7830825821345084678),
        name: 'name',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 5175169132333483920),
        name: 'shortTitle',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 1823838358828141343),
        name: 'url',
        type: 9,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(3, 632897400116191682),
    name: 'Book',
    lastPropertyId: const obx_int.IdUid(4, 7590958039596659276),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 2182849118345249687),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 1345327414389662044),
        name: 'name',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 7423833366970731845),
        name: 'bookId',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 7590958039596659276),
        name: 'bibleVersionId',
        type: 11,
        flags: 520,
        indexId: const obx_int.IdUid(1, 4839987404204600079),
        relationTarget: 'BibleVersion',
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[
      obx_int.ModelBacklink(
        name: 'chapters',
        srcEntity: 'Chapter',
        srcField: '',
      ),
    ],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(4, 5583908575714125936),
    name: 'Chapter',
    lastPropertyId: const obx_int.IdUid(3, 5440240783921885392),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 6690143459373749218),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 7643872646773682691),
        name: 'chapterNumber',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 5440240783921885392),
        name: 'bookId',
        type: 11,
        flags: 520,
        indexId: const obx_int.IdUid(2, 1996137536489274746),
        relationTarget: 'Book',
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[
      obx_int.ModelBacklink(name: 'verses', srcEntity: 'Verse', srcField: ''),
    ],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(5, 5015272691222161237),
    name: 'CreatedTopicsEn',
    lastPropertyId: const obx_int.IdUid(3, 182445421120377134),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 8467280048191278256),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 3589334218978845453),
        name: 'title',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 182445421120377134),
        name: 'verses',
        type: 30,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(6, 2898916156245750764),
    name: 'CrossReference',
    lastPropertyId: const obx_int.IdUid(3, 2066651317205341800),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 2408120368532846892),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 1993320119600450684),
        name: 'verse',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 2066651317205341800),
        name: 'toVerse',
        type: 9,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(7, 7718477215402508837),
    name: 'Footnote',
    lastPropertyId: const obx_int.IdUid(4, 6645492359522258364),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 5141279664119607116),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 6807243844871553504),
        name: 'caller',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 1855228678733929852),
        name: 'text',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 6645492359522258364),
        name: 'verseId',
        type: 11,
        flags: 520,
        indexId: const obx_int.IdUid(3, 4383555206662223006),
        relationTarget: 'Verse',
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(8, 446198373362083281),
    name: 'GeneratedTopicsEn',
    lastPropertyId: const obx_int.IdUid(3, 8079327434059729298),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 8141148930195275281),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 1782998081796368611),
        name: 'title',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 8079327434059729298),
        name: 'verses',
        type: 30,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(9, 4529207718811388551),
    name: 'GoArea',
    lastPropertyId: const obx_int.IdUid(4, 2854006788377371403),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 2753594713583496124),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 3844694456826506981),
        name: 'name',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 7669469997142039547),
        name: 'latitudes',
        type: 29,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 2854006788377371403),
        name: 'longitudes',
        type: 29,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(10, 9050167815051126382),
    name: 'GoChurch',
    lastPropertyId: const obx_int.IdUid(9, 7011128721977868526),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 4816657631113734503),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 4139593617482003121),
        name: 'churchName',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 675554378481446696),
        name: 'pastorName',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 1822123498421152407),
        name: 'address',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 2696937844163080840),
        name: 'phone',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 1059731731052187383),
        name: 'email',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 6675250282075235480),
        name: 'latitude',
        type: 8,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(8, 5833865899566352569),
        name: 'longitude',
        type: 8,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(9, 7011128721977868526),
        name: 'financialStatus',
        type: 9,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[
      obx_int.ModelRelation(
        id: const obx_int.IdUid(1, 4396916895929458233),
        name: 'notes',
        targetId: const obx_int.IdUid(11, 3187118928482488246),
      ),
    ],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(11, 3187118928482488246),
    name: 'GoChurchNote',
    lastPropertyId: const obx_int.IdUid(5, 4978507679229509884),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 6275887044051280089),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 506226691034206616),
        name: 'content',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 7538423472700016522),
        name: 'createdAt',
        type: 10,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 7933103001273202902),
        name: 'updatedAt',
        type: 10,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 4978507679229509884),
        name: 'churchId',
        type: 11,
        flags: 520,
        indexId: const obx_int.IdUid(4, 5740186171643366795),
        relationTarget: 'GoChurch',
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(12, 4310268094882542528),
    name: 'GoContact',
    lastPropertyId: const obx_int.IdUid(10, 4996577697653661190),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 8322415055499582866),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 4423141271803697758),
        name: 'fullName',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 4433964505907597937),
        name: 'latitude',
        type: 8,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 564084436198204526),
        name: 'longitude',
        type: 8,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 3433108112766460983),
        name: 'address',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 117904593377937112),
        name: 'birthday',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 6110373528986153230),
        name: 'phone',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(8, 4898845177862891906),
        name: 'email',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(9, 2430082559686876329),
        name: 'isVisited',
        type: 1,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(10, 4996577697653661190),
        name: 'eternalStatus',
        type: 9,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[
      obx_int.ModelRelation(
        id: const obx_int.IdUid(2, 5634087120853118907),
        name: 'notes',
        targetId: const obx_int.IdUid(13, 1021988363020324923),
      ),
    ],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(13, 1021988363020324923),
    name: 'GoContactNote',
    lastPropertyId: const obx_int.IdUid(5, 274901198144976813),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 6982098349154144587),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 6750920944171757543),
        name: 'content',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 2000223667091272613),
        name: 'createdAt',
        type: 10,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 5624536181391606701),
        name: 'updatedAt',
        type: 10,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 274901198144976813),
        name: 'contactId',
        type: 11,
        flags: 520,
        indexId: const obx_int.IdUid(5, 7410384448691956502),
        relationTarget: 'GoContact',
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(14, 2781705575614970030),
    name: 'GoMapInfo',
    lastPropertyId: const obx_int.IdUid(8, 1324622822835533363),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 2889481607852424745),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 7845534794445328759),
        name: 'name',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 7944033000140970695),
        name: 'filePath',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 6958477472211398153),
        name: 'downloadUrl',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 4385802635671033006),
        name: 'isTemporary',
        type: 1,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 8660555406743659705),
        name: 'latitude',
        type: 8,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 4539486398594620195),
        name: 'longitude',
        type: 8,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(8, 1324622822835533363),
        name: 'zoomLevel',
        type: 6,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(15, 4271575965899503196),
    name: 'GoMinistry',
    lastPropertyId: const obx_int.IdUid(9, 7896320531472857892),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 8120829046099358846),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 3669599829310801653),
        name: 'ministryName',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 2761573611588465022),
        name: 'contactName',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 2878263018399388279),
        name: 'address',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 7748655423210925804),
        name: 'phone',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 2535660470383220017),
        name: 'email',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 1328375392968958456),
        name: 'latitude',
        type: 8,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(8, 5069181304438075004),
        name: 'longitude',
        type: 8,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(9, 7896320531472857892),
        name: 'partnerStatus',
        type: 9,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[
      obx_int.ModelRelation(
        id: const obx_int.IdUid(3, 5039034381428715367),
        name: 'notes',
        targetId: const obx_int.IdUid(16, 7849845022116363071),
      ),
    ],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(16, 7849845022116363071),
    name: 'GoMinistryNote',
    lastPropertyId: const obx_int.IdUid(5, 888624983557033583),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 8509516901547618554),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 7080342877391700320),
        name: 'content',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 8965509630886364639),
        name: 'createdAt',
        type: 10,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 5909458878532571214),
        name: 'updatedAt',
        type: 10,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 888624983557033583),
        name: 'ministryId',
        type: 11,
        flags: 520,
        indexId: const obx_int.IdUid(6, 7578185356449810176),
        relationTarget: 'GoMinistry',
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(17, 4541728444952466447),
    name: 'GoStreet',
    lastPropertyId: const obx_int.IdUid(5, 6479846162864146030),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 734629648485858033),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 1591479505364564350),
        name: 'name',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 6366779303964285270),
        name: 'latitudes',
        type: 29,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 6885904136564035847),
        name: 'longitudes',
        type: 29,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 6479846162864146030),
        name: 'type',
        type: 9,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(18, 3492678653612580808),
    name: 'GoZone',
    lastPropertyId: const obx_int.IdUid(6, 8175293783292145656),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 3992837180523529720),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 41375539639680432),
        name: 'name',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 5975453316285605520),
        name: 'latitude',
        type: 8,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 4367450096593289228),
        name: 'longitude',
        type: 8,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 6164273567610086089),
        name: 'widthInMeters',
        type: 8,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 8175293783292145656),
        name: 'heightInMeters',
        type: 8,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(19, 3473353138959201891),
    name: 'StrongsEntry',
    lastPropertyId: const obx_int.IdUid(5, 2675601190473481080),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 5203674904039171418),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 8065415786879369041),
        name: 'strongsNumber',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 5611873564349020065),
        name: 'word',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 5982835118968764132),
        name: 'position',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 2675601190473481080),
        name: 'verseId',
        type: 11,
        flags: 520,
        indexId: const obx_int.IdUid(7, 6700868747990294707),
        relationTarget: 'Verse',
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(20, 2445957613442893363),
    name: 'UserPreferences',
    lastPropertyId: const obx_int.IdUid(6, 4641220943858618153),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 465023579265105164),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 6270964422875235107),
        name: 'currentMap',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 7561483636291680850),
        name: 'fontFamily',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 3068990223826082298),
        name: 'fontSize',
        type: 8,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 7337930780489079905),
        name: 'languageCode',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 4641220943858618153),
        name: 'currentBibleVersionId',
        type: 6,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(21, 4038429996045323762),
    name: 'Verse',
    lastPropertyId: const obx_int.IdUid(4, 4737580920355391359),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 2237240516599906553),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 6626631386975769348),
        name: 'verseNumber',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 6585398065353869016),
        name: 'text',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 4737580920355391359),
        name: 'chapterId',
        type: 11,
        flags: 520,
        indexId: const obx_int.IdUid(8, 4270293699924788037),
        relationTarget: 'Chapter',
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[
      obx_int.ModelBacklink(
        name: 'strongsEntries',
        srcEntity: 'StrongsEntry',
        srcField: '',
      ),
      obx_int.ModelBacklink(
        name: 'footnotes',
        srcEntity: 'Footnote',
        srcField: '',
      ),
    ],
  ),
];

/// Shortcut for [obx.Store.new] that passes [getObjectBoxModel] and for Flutter
/// apps by default a [directory] using `defaultStoreDirectory()` from the
/// ObjectBox Flutter library.
///
/// Note: for desktop apps it is recommended to specify a unique [directory].
///
/// See [obx.Store.new] for an explanation of all parameters.
///
/// For Flutter apps, also calls `loadObjectBoxLibraryAndroidCompat()` from
/// the ObjectBox Flutter library to fix loading the native ObjectBox library
/// on Android 6 and older.
Future<obx.Store> openStore({
  String? directory,
  int? maxDBSizeInKB,
  int? maxDataSizeInKB,
  int? fileMode,
  int? maxReaders,
  bool queriesCaseSensitiveDefault = true,
  String? macosApplicationGroup,
}) async {
  await loadObjectBoxLibraryAndroidCompat();
  return obx.Store(
    getObjectBoxModel(),
    directory: directory ?? (await defaultStoreDirectory()).path,
    maxDBSizeInKB: maxDBSizeInKB,
    maxDataSizeInKB: maxDataSizeInKB,
    fileMode: fileMode,
    maxReaders: maxReaders,
    queriesCaseSensitiveDefault: queriesCaseSensitiveDefault,
    macosApplicationGroup: macosApplicationGroup,
  );
}

/// Returns the ObjectBox model definition for this project for use with
/// [obx.Store.new].
obx_int.ModelDefinition getObjectBoxModel() {
  final model = obx_int.ModelInfo(
    entities: _entities,
    lastEntityId: const obx_int.IdUid(21, 4038429996045323762),
    lastIndexId: const obx_int.IdUid(8, 4270293699924788037),
    lastRelationId: const obx_int.IdUid(3, 5039034381428715367),
    lastSequenceId: const obx_int.IdUid(0, 0),
    retiredEntityUids: const [],
    retiredIndexUids: const [],
    retiredPropertyUids: const [],
    retiredRelationUids: const [],
    modelVersion: 5,
    modelVersionParserMinimum: 5,
    version: 1,
  );

  final bindings = <Type, obx_int.EntityDefinition>{
    BibleVersion: obx_int.EntityDefinition<BibleVersion>(
      model: _entities[0],
      toOneRelations: (BibleVersion object) => [],
      toManyRelations: (BibleVersion object) => {
        obx_int.RelInfo<Book>.toOneBacklink(
          4,
          object.id,
          (Book srcObject) => srcObject.bibleVersion,
        ): object.books,
      },
      getId: (BibleVersion object) => object.id,
      setId: (BibleVersion object, int id) {
        object.id = id;
      },
      objectToFB: (BibleVersion object, fb.Builder fbb) {
        final nameOffset = fbb.writeString(object.name);
        final languageCodeOffset = fbb.writeString(object.languageCode);
        fbb.startTable(4);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, nameOffset);
        fbb.addOffset(2, languageCodeOffset);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final nameParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final languageCodeParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 8, '');
        final object = BibleVersion(
          id: idParam,
          name: nameParam,
          languageCode: languageCodeParam,
        );
        obx_int.InternalToManyAccess.setRelInfo<BibleVersion>(
          object.books,
          store,
          obx_int.RelInfo<Book>.toOneBacklink(
            4,
            object.id,
            (Book srcObject) => srcObject.bibleVersion,
          ),
        );
        return object;
      },
    ),
    BiblesDownload: obx_int.EntityDefinition<BiblesDownload>(
      model: _entities[1],
      toOneRelations: (BiblesDownload object) => [],
      toManyRelations: (BiblesDownload object) => {},
      getId: (BiblesDownload object) => object.id,
      setId: (BiblesDownload object, int id) {
        object.id = id;
      },
      objectToFB: (BiblesDownload object, fb.Builder fbb) {
        final nameOffset = fbb.writeString(object.name);
        final shortTitleOffset = fbb.writeString(object.shortTitle);
        final urlOffset = fbb.writeString(object.url);
        fbb.startTable(5);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, nameOffset);
        fbb.addOffset(2, shortTitleOffset);
        fbb.addOffset(3, urlOffset);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final nameParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final shortTitleParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 8, '');
        final urlParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 10, '');
        final object = BiblesDownload(
          id: idParam,
          name: nameParam,
          shortTitle: shortTitleParam,
          url: urlParam,
        );

        return object;
      },
    ),
    Book: obx_int.EntityDefinition<Book>(
      model: _entities[2],
      toOneRelations: (Book object) => [object.bibleVersion],
      toManyRelations: (Book object) => {
        obx_int.RelInfo<Chapter>.toOneBacklink(
          3,
          object.id,
          (Chapter srcObject) => srcObject.book,
        ): object.chapters,
      },
      getId: (Book object) => object.id,
      setId: (Book object, int id) {
        object.id = id;
      },
      objectToFB: (Book object, fb.Builder fbb) {
        final nameOffset = fbb.writeString(object.name);
        final bookIdOffset = fbb.writeString(object.bookId);
        fbb.startTable(5);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, nameOffset);
        fbb.addOffset(2, bookIdOffset);
        fbb.addInt64(3, object.bibleVersion.targetId);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final nameParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final bookIdParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 8, '');
        final object = Book(id: idParam, name: nameParam, bookId: bookIdParam);
        object.bibleVersion.targetId = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          10,
          0,
        );
        object.bibleVersion.attach(store);
        obx_int.InternalToManyAccess.setRelInfo<Book>(
          object.chapters,
          store,
          obx_int.RelInfo<Chapter>.toOneBacklink(
            3,
            object.id,
            (Chapter srcObject) => srcObject.book,
          ),
        );
        return object;
      },
    ),
    Chapter: obx_int.EntityDefinition<Chapter>(
      model: _entities[3],
      toOneRelations: (Chapter object) => [object.book],
      toManyRelations: (Chapter object) => {
        obx_int.RelInfo<Verse>.toOneBacklink(
          4,
          object.id,
          (Verse srcObject) => srcObject.chapter,
        ): object.verses,
      },
      getId: (Chapter object) => object.id,
      setId: (Chapter object, int id) {
        object.id = id;
      },
      objectToFB: (Chapter object, fb.Builder fbb) {
        fbb.startTable(4);
        fbb.addInt64(0, object.id);
        fbb.addInt64(1, object.chapterNumber);
        fbb.addInt64(2, object.book.targetId);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final chapterNumberParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          6,
          0,
        );
        final object = Chapter(id: idParam, chapterNumber: chapterNumberParam);
        object.book.targetId = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          8,
          0,
        );
        object.book.attach(store);
        obx_int.InternalToManyAccess.setRelInfo<Chapter>(
          object.verses,
          store,
          obx_int.RelInfo<Verse>.toOneBacklink(
            4,
            object.id,
            (Verse srcObject) => srcObject.chapter,
          ),
        );
        return object;
      },
    ),
    CreatedTopicsEn: obx_int.EntityDefinition<CreatedTopicsEn>(
      model: _entities[4],
      toOneRelations: (CreatedTopicsEn object) => [],
      toManyRelations: (CreatedTopicsEn object) => {},
      getId: (CreatedTopicsEn object) => object.id,
      setId: (CreatedTopicsEn object, int id) {
        object.id = id;
      },
      objectToFB: (CreatedTopicsEn object, fb.Builder fbb) {
        final titleOffset = fbb.writeString(object.title);
        final versesOffset = fbb.writeList(
          object.verses.map(fbb.writeString).toList(growable: false),
        );
        fbb.startTable(4);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, titleOffset);
        fbb.addOffset(2, versesOffset);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final titleParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final versesParam = const fb.ListReader<String>(
          fb.StringReader(asciiOptimization: true),
          lazy: false,
        ).vTableGet(buffer, rootOffset, 8, []);
        final object = CreatedTopicsEn(title: titleParam, verses: versesParam)
          ..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);

        return object;
      },
    ),
    CrossReference: obx_int.EntityDefinition<CrossReference>(
      model: _entities[5],
      toOneRelations: (CrossReference object) => [],
      toManyRelations: (CrossReference object) => {},
      getId: (CrossReference object) => object.id,
      setId: (CrossReference object, int id) {
        object.id = id;
      },
      objectToFB: (CrossReference object, fb.Builder fbb) {
        final verseOffset = fbb.writeString(object.verse);
        final toVerseOffset = fbb.writeString(object.toVerse);
        fbb.startTable(4);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, verseOffset);
        fbb.addOffset(2, toVerseOffset);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final verseParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final toVerseParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 8, '');
        final object = CrossReference(verse: verseParam, toVerse: toVerseParam)
          ..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);

        return object;
      },
    ),
    Footnote: obx_int.EntityDefinition<Footnote>(
      model: _entities[6],
      toOneRelations: (Footnote object) => [object.verse],
      toManyRelations: (Footnote object) => {},
      getId: (Footnote object) => object.id,
      setId: (Footnote object, int id) {
        object.id = id;
      },
      objectToFB: (Footnote object, fb.Builder fbb) {
        final callerOffset = fbb.writeString(object.caller);
        final textOffset = fbb.writeString(object.text);
        fbb.startTable(5);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, callerOffset);
        fbb.addOffset(2, textOffset);
        fbb.addInt64(3, object.verse.targetId);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final callerParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final textParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 8, '');
        final object = Footnote(
          id: idParam,
          caller: callerParam,
          text: textParam,
        );
        object.verse.targetId = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          10,
          0,
        );
        object.verse.attach(store);
        return object;
      },
    ),
    GeneratedTopicsEn: obx_int.EntityDefinition<GeneratedTopicsEn>(
      model: _entities[7],
      toOneRelations: (GeneratedTopicsEn object) => [],
      toManyRelations: (GeneratedTopicsEn object) => {},
      getId: (GeneratedTopicsEn object) => object.id,
      setId: (GeneratedTopicsEn object, int id) {
        object.id = id;
      },
      objectToFB: (GeneratedTopicsEn object, fb.Builder fbb) {
        final titleOffset = fbb.writeString(object.title);
        final versesOffset = fbb.writeList(
          object.verses.map(fbb.writeString).toList(growable: false),
        );
        fbb.startTable(4);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, titleOffset);
        fbb.addOffset(2, versesOffset);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final titleParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final versesParam = const fb.ListReader<String>(
          fb.StringReader(asciiOptimization: true),
          lazy: false,
        ).vTableGet(buffer, rootOffset, 8, []);
        final object = GeneratedTopicsEn(title: titleParam, verses: versesParam)
          ..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);

        return object;
      },
    ),
    GoArea: obx_int.EntityDefinition<GoArea>(
      model: _entities[8],
      toOneRelations: (GoArea object) => [],
      toManyRelations: (GoArea object) => {},
      getId: (GoArea object) => object.id,
      setId: (GoArea object, int id) {
        object.id = id;
      },
      objectToFB: (GoArea object, fb.Builder fbb) {
        final nameOffset = fbb.writeString(object.name);
        final latitudesOffset = fbb.writeListFloat64(object.latitudes);
        final longitudesOffset = fbb.writeListFloat64(object.longitudes);
        fbb.startTable(5);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, nameOffset);
        fbb.addOffset(2, latitudesOffset);
        fbb.addOffset(3, longitudesOffset);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final nameParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final latitudesParam = const fb.ListReader<double>(
          fb.Float64Reader(),
          lazy: false,
        ).vTableGet(buffer, rootOffset, 8, []);
        final longitudesParam = const fb.ListReader<double>(
          fb.Float64Reader(),
          lazy: false,
        ).vTableGet(buffer, rootOffset, 10, []);
        final object = GoArea(
          id: idParam,
          name: nameParam,
          latitudes: latitudesParam,
          longitudes: longitudesParam,
        );

        return object;
      },
    ),
    GoChurch: obx_int.EntityDefinition<GoChurch>(
      model: _entities[9],
      toOneRelations: (GoChurch object) => [],
      toManyRelations: (GoChurch object) => {
        obx_int.RelInfo<GoChurch>.toMany(1, object.id): object.notes,
      },
      getId: (GoChurch object) => object.id,
      setId: (GoChurch object, int id) {
        object.id = id;
      },
      objectToFB: (GoChurch object, fb.Builder fbb) {
        final churchNameOffset = fbb.writeString(object.churchName);
        final pastorNameOffset = object.pastorName == null
            ? null
            : fbb.writeString(object.pastorName!);
        final addressOffset = object.address == null
            ? null
            : fbb.writeString(object.address!);
        final phoneOffset = object.phone == null
            ? null
            : fbb.writeString(object.phone!);
        final emailOffset = object.email == null
            ? null
            : fbb.writeString(object.email!);
        final financialStatusOffset = object.financialStatus == null
            ? null
            : fbb.writeString(object.financialStatus!);
        fbb.startTable(10);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, churchNameOffset);
        fbb.addOffset(2, pastorNameOffset);
        fbb.addOffset(3, addressOffset);
        fbb.addOffset(4, phoneOffset);
        fbb.addOffset(5, emailOffset);
        fbb.addFloat64(6, object.latitude);
        fbb.addFloat64(7, object.longitude);
        fbb.addOffset(8, financialStatusOffset);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final churchNameParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final pastorNameParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 8);
        final addressParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 10);
        final phoneParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 12);
        final emailParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 14);
        final latitudeParam = const fb.Float64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          16,
        );
        final longitudeParam = const fb.Float64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          18,
        );
        final financialStatusParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 20);
        final object = GoChurch(
          id: idParam,
          churchName: churchNameParam,
          pastorName: pastorNameParam,
          address: addressParam,
          phone: phoneParam,
          email: emailParam,
          latitude: latitudeParam,
          longitude: longitudeParam,
          financialStatus: financialStatusParam,
        );
        obx_int.InternalToManyAccess.setRelInfo<GoChurch>(
          object.notes,
          store,
          obx_int.RelInfo<GoChurch>.toMany(1, object.id),
        );
        return object;
      },
    ),
    GoChurchNote: obx_int.EntityDefinition<GoChurchNote>(
      model: _entities[10],
      toOneRelations: (GoChurchNote object) => [object.church],
      toManyRelations: (GoChurchNote object) => {},
      getId: (GoChurchNote object) => object.id,
      setId: (GoChurchNote object, int id) {
        object.id = id;
      },
      objectToFB: (GoChurchNote object, fb.Builder fbb) {
        final contentOffset = fbb.writeString(object.content);
        fbb.startTable(6);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, contentOffset);
        fbb.addInt64(2, object.createdAt.millisecondsSinceEpoch);
        fbb.addInt64(3, object.updatedAt?.millisecondsSinceEpoch);
        fbb.addInt64(4, object.church.targetId);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final updatedAtValue = const fb.Int64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          10,
        );
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final contentParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final createdAtParam = DateTime.fromMillisecondsSinceEpoch(
          const fb.Int64Reader().vTableGet(buffer, rootOffset, 8, 0),
        );
        final updatedAtParam = updatedAtValue == null
            ? null
            : DateTime.fromMillisecondsSinceEpoch(updatedAtValue);
        final object = GoChurchNote(
          id: idParam,
          content: contentParam,
          createdAt: createdAtParam,
          updatedAt: updatedAtParam,
        );
        object.church.targetId = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          12,
          0,
        );
        object.church.attach(store);
        return object;
      },
    ),
    GoContact: obx_int.EntityDefinition<GoContact>(
      model: _entities[11],
      toOneRelations: (GoContact object) => [],
      toManyRelations: (GoContact object) => {
        obx_int.RelInfo<GoContact>.toMany(2, object.id): object.notes,
      },
      getId: (GoContact object) => object.id,
      setId: (GoContact object, int id) {
        object.id = id;
      },
      objectToFB: (GoContact object, fb.Builder fbb) {
        final fullNameOffset = fbb.writeString(object.fullName);
        final addressOffset = object.address == null
            ? null
            : fbb.writeString(object.address!);
        final birthdayOffset = object.birthday == null
            ? null
            : fbb.writeString(object.birthday!);
        final phoneOffset = object.phone == null
            ? null
            : fbb.writeString(object.phone!);
        final emailOffset = object.email == null
            ? null
            : fbb.writeString(object.email!);
        final eternalStatusOffset = object.eternalStatus == null
            ? null
            : fbb.writeString(object.eternalStatus!);
        fbb.startTable(11);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, fullNameOffset);
        fbb.addFloat64(2, object.latitude);
        fbb.addFloat64(3, object.longitude);
        fbb.addOffset(4, addressOffset);
        fbb.addOffset(5, birthdayOffset);
        fbb.addOffset(6, phoneOffset);
        fbb.addOffset(7, emailOffset);
        fbb.addBool(8, object.isVisited);
        fbb.addOffset(9, eternalStatusOffset);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final fullNameParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final latitudeParam = const fb.Float64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          8,
        );
        final longitudeParam = const fb.Float64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          10,
        );
        final addressParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 12);
        final birthdayParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 14);
        final phoneParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 16);
        final emailParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 18);
        final isVisitedParam = const fb.BoolReader().vTableGet(
          buffer,
          rootOffset,
          20,
          false,
        );
        final eternalStatusParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 22);
        final object = GoContact(
          id: idParam,
          fullName: fullNameParam,
          latitude: latitudeParam,
          longitude: longitudeParam,
          address: addressParam,
          birthday: birthdayParam,
          phone: phoneParam,
          email: emailParam,
          isVisited: isVisitedParam,
          eternalStatus: eternalStatusParam,
        );
        obx_int.InternalToManyAccess.setRelInfo<GoContact>(
          object.notes,
          store,
          obx_int.RelInfo<GoContact>.toMany(2, object.id),
        );
        return object;
      },
    ),
    GoContactNote: obx_int.EntityDefinition<GoContactNote>(
      model: _entities[12],
      toOneRelations: (GoContactNote object) => [object.contact],
      toManyRelations: (GoContactNote object) => {},
      getId: (GoContactNote object) => object.id,
      setId: (GoContactNote object, int id) {
        object.id = id;
      },
      objectToFB: (GoContactNote object, fb.Builder fbb) {
        final contentOffset = fbb.writeString(object.content);
        fbb.startTable(6);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, contentOffset);
        fbb.addInt64(2, object.createdAt.millisecondsSinceEpoch);
        fbb.addInt64(3, object.updatedAt?.millisecondsSinceEpoch);
        fbb.addInt64(4, object.contact.targetId);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final updatedAtValue = const fb.Int64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          10,
        );
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final contentParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final createdAtParam = DateTime.fromMillisecondsSinceEpoch(
          const fb.Int64Reader().vTableGet(buffer, rootOffset, 8, 0),
        );
        final updatedAtParam = updatedAtValue == null
            ? null
            : DateTime.fromMillisecondsSinceEpoch(updatedAtValue);
        final object = GoContactNote(
          id: idParam,
          content: contentParam,
          createdAt: createdAtParam,
          updatedAt: updatedAtParam,
        );
        object.contact.targetId = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          12,
          0,
        );
        object.contact.attach(store);
        return object;
      },
    ),
    GoMapInfo: obx_int.EntityDefinition<GoMapInfo>(
      model: _entities[13],
      toOneRelations: (GoMapInfo object) => [],
      toManyRelations: (GoMapInfo object) => {},
      getId: (GoMapInfo object) => object.id,
      setId: (GoMapInfo object, int id) {
        object.id = id;
      },
      objectToFB: (GoMapInfo object, fb.Builder fbb) {
        final nameOffset = fbb.writeString(object.name);
        final filePathOffset = object.filePath == null
            ? null
            : fbb.writeString(object.filePath!);
        final downloadUrlOffset = object.downloadUrl == null
            ? null
            : fbb.writeString(object.downloadUrl!);
        fbb.startTable(9);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, nameOffset);
        fbb.addOffset(2, filePathOffset);
        fbb.addOffset(3, downloadUrlOffset);
        fbb.addBool(4, object.isTemporary);
        fbb.addFloat64(5, object.latitude);
        fbb.addFloat64(6, object.longitude);
        fbb.addInt64(7, object.zoomLevel);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final nameParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final filePathParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 8);
        final downloadUrlParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 10);
        final isTemporaryParam = const fb.BoolReader().vTableGetNullable(
          buffer,
          rootOffset,
          12,
        );
        final latitudeParam = const fb.Float64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          14,
        );
        final longitudeParam = const fb.Float64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          16,
        );
        final zoomLevelParam = const fb.Int64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          18,
        );
        final object = GoMapInfo(
          id: idParam,
          name: nameParam,
          filePath: filePathParam,
          downloadUrl: downloadUrlParam,
          isTemporary: isTemporaryParam,
          latitude: latitudeParam,
          longitude: longitudeParam,
          zoomLevel: zoomLevelParam,
        );

        return object;
      },
    ),
    GoMinistry: obx_int.EntityDefinition<GoMinistry>(
      model: _entities[14],
      toOneRelations: (GoMinistry object) => [],
      toManyRelations: (GoMinistry object) => {
        obx_int.RelInfo<GoMinistry>.toMany(3, object.id): object.notes,
      },
      getId: (GoMinistry object) => object.id,
      setId: (GoMinistry object, int id) {
        object.id = id;
      },
      objectToFB: (GoMinistry object, fb.Builder fbb) {
        final ministryNameOffset = fbb.writeString(object.ministryName);
        final contactNameOffset = object.contactName == null
            ? null
            : fbb.writeString(object.contactName!);
        final addressOffset = object.address == null
            ? null
            : fbb.writeString(object.address!);
        final phoneOffset = object.phone == null
            ? null
            : fbb.writeString(object.phone!);
        final emailOffset = object.email == null
            ? null
            : fbb.writeString(object.email!);
        final partnerStatusOffset = object.partnerStatus == null
            ? null
            : fbb.writeString(object.partnerStatus!);
        fbb.startTable(10);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, ministryNameOffset);
        fbb.addOffset(2, contactNameOffset);
        fbb.addOffset(3, addressOffset);
        fbb.addOffset(4, phoneOffset);
        fbb.addOffset(5, emailOffset);
        fbb.addFloat64(6, object.latitude);
        fbb.addFloat64(7, object.longitude);
        fbb.addOffset(8, partnerStatusOffset);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final ministryNameParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final contactNameParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 8);
        final addressParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 10);
        final phoneParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 12);
        final emailParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 14);
        final latitudeParam = const fb.Float64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          16,
        );
        final longitudeParam = const fb.Float64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          18,
        );
        final partnerStatusParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 20);
        final object = GoMinistry(
          id: idParam,
          ministryName: ministryNameParam,
          contactName: contactNameParam,
          address: addressParam,
          phone: phoneParam,
          email: emailParam,
          latitude: latitudeParam,
          longitude: longitudeParam,
          partnerStatus: partnerStatusParam,
        );
        obx_int.InternalToManyAccess.setRelInfo<GoMinistry>(
          object.notes,
          store,
          obx_int.RelInfo<GoMinistry>.toMany(3, object.id),
        );
        return object;
      },
    ),
    GoMinistryNote: obx_int.EntityDefinition<GoMinistryNote>(
      model: _entities[15],
      toOneRelations: (GoMinistryNote object) => [object.ministry],
      toManyRelations: (GoMinistryNote object) => {},
      getId: (GoMinistryNote object) => object.id,
      setId: (GoMinistryNote object, int id) {
        object.id = id;
      },
      objectToFB: (GoMinistryNote object, fb.Builder fbb) {
        final contentOffset = fbb.writeString(object.content);
        fbb.startTable(6);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, contentOffset);
        fbb.addInt64(2, object.createdAt.millisecondsSinceEpoch);
        fbb.addInt64(3, object.updatedAt?.millisecondsSinceEpoch);
        fbb.addInt64(4, object.ministry.targetId);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final updatedAtValue = const fb.Int64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          10,
        );
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final contentParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final createdAtParam = DateTime.fromMillisecondsSinceEpoch(
          const fb.Int64Reader().vTableGet(buffer, rootOffset, 8, 0),
        );
        final updatedAtParam = updatedAtValue == null
            ? null
            : DateTime.fromMillisecondsSinceEpoch(updatedAtValue);
        final object = GoMinistryNote(
          id: idParam,
          content: contentParam,
          createdAt: createdAtParam,
          updatedAt: updatedAtParam,
        );
        object.ministry.targetId = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          12,
          0,
        );
        object.ministry.attach(store);
        return object;
      },
    ),
    GoStreet: obx_int.EntityDefinition<GoStreet>(
      model: _entities[16],
      toOneRelations: (GoStreet object) => [],
      toManyRelations: (GoStreet object) => {},
      getId: (GoStreet object) => object.id,
      setId: (GoStreet object, int id) {
        object.id = id;
      },
      objectToFB: (GoStreet object, fb.Builder fbb) {
        final nameOffset = fbb.writeString(object.name);
        final latitudesOffset = fbb.writeListFloat64(object.latitudes);
        final longitudesOffset = fbb.writeListFloat64(object.longitudes);
        final typeOffset = object.type == null
            ? null
            : fbb.writeString(object.type!);
        fbb.startTable(6);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, nameOffset);
        fbb.addOffset(2, latitudesOffset);
        fbb.addOffset(3, longitudesOffset);
        fbb.addOffset(4, typeOffset);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final nameParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final latitudesParam = const fb.ListReader<double>(
          fb.Float64Reader(),
          lazy: false,
        ).vTableGet(buffer, rootOffset, 8, []);
        final longitudesParam = const fb.ListReader<double>(
          fb.Float64Reader(),
          lazy: false,
        ).vTableGet(buffer, rootOffset, 10, []);
        final typeParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 12);
        final object = GoStreet(
          id: idParam,
          name: nameParam,
          latitudes: latitudesParam,
          longitudes: longitudesParam,
          type: typeParam,
        );

        return object;
      },
    ),
    GoZone: obx_int.EntityDefinition<GoZone>(
      model: _entities[17],
      toOneRelations: (GoZone object) => [],
      toManyRelations: (GoZone object) => {},
      getId: (GoZone object) => object.id,
      setId: (GoZone object, int id) {
        object.id = id;
      },
      objectToFB: (GoZone object, fb.Builder fbb) {
        final nameOffset = fbb.writeString(object.name);
        fbb.startTable(7);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, nameOffset);
        fbb.addFloat64(2, object.latitude);
        fbb.addFloat64(3, object.longitude);
        fbb.addFloat64(4, object.widthInMeters);
        fbb.addFloat64(5, object.heightInMeters);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final nameParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final latitudeParam = const fb.Float64Reader().vTableGet(
          buffer,
          rootOffset,
          8,
          0,
        );
        final longitudeParam = const fb.Float64Reader().vTableGet(
          buffer,
          rootOffset,
          10,
          0,
        );
        final widthInMetersParam = const fb.Float64Reader().vTableGet(
          buffer,
          rootOffset,
          12,
          0,
        );
        final heightInMetersParam = const fb.Float64Reader().vTableGet(
          buffer,
          rootOffset,
          14,
          0,
        );
        final object = GoZone(
          id: idParam,
          name: nameParam,
          latitude: latitudeParam,
          longitude: longitudeParam,
          widthInMeters: widthInMetersParam,
          heightInMeters: heightInMetersParam,
        );

        return object;
      },
    ),
    StrongsEntry: obx_int.EntityDefinition<StrongsEntry>(
      model: _entities[18],
      toOneRelations: (StrongsEntry object) => [object.verse],
      toManyRelations: (StrongsEntry object) => {},
      getId: (StrongsEntry object) => object.id,
      setId: (StrongsEntry object, int id) {
        object.id = id;
      },
      objectToFB: (StrongsEntry object, fb.Builder fbb) {
        final strongsNumberOffset = fbb.writeString(object.strongsNumber);
        final wordOffset = fbb.writeString(object.word);
        fbb.startTable(6);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, strongsNumberOffset);
        fbb.addOffset(2, wordOffset);
        fbb.addInt64(3, object.position);
        fbb.addInt64(4, object.verse.targetId);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final strongsNumberParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final wordParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 8, '');
        final positionParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          10,
          0,
        );
        final object = StrongsEntry(
          id: idParam,
          strongsNumber: strongsNumberParam,
          word: wordParam,
          position: positionParam,
        );
        object.verse.targetId = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          12,
          0,
        );
        object.verse.attach(store);
        return object;
      },
    ),
    UserPreferences: obx_int.EntityDefinition<UserPreferences>(
      model: _entities[19],
      toOneRelations: (UserPreferences object) => [],
      toManyRelations: (UserPreferences object) => {},
      getId: (UserPreferences object) => object.id,
      setId: (UserPreferences object, int id) {
        object.id = id;
      },
      objectToFB: (UserPreferences object, fb.Builder fbb) {
        final currentMapOffset = object.currentMap == null
            ? null
            : fbb.writeString(object.currentMap!);
        final fontFamilyOffset = object.fontFamily == null
            ? null
            : fbb.writeString(object.fontFamily!);
        final languageCodeOffset = object.languageCode == null
            ? null
            : fbb.writeString(object.languageCode!);
        fbb.startTable(7);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, currentMapOffset);
        fbb.addOffset(2, fontFamilyOffset);
        fbb.addFloat64(3, object.fontSize);
        fbb.addOffset(4, languageCodeOffset);
        fbb.addInt64(5, object.currentBibleVersionId);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final currentMapParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 6);
        final fontFamilyParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 8);
        final fontSizeParam = const fb.Float64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          10,
        );
        final languageCodeParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 12);
        final currentBibleVersionIdParam = const fb.Int64Reader()
            .vTableGetNullable(buffer, rootOffset, 14);
        final object = UserPreferences(
          id: idParam,
          currentMap: currentMapParam,
          fontFamily: fontFamilyParam,
          fontSize: fontSizeParam,
          languageCode: languageCodeParam,
          currentBibleVersionId: currentBibleVersionIdParam,
        );

        return object;
      },
    ),
    Verse: obx_int.EntityDefinition<Verse>(
      model: _entities[20],
      toOneRelations: (Verse object) => [object.chapter],
      toManyRelations: (Verse object) => {
        obx_int.RelInfo<StrongsEntry>.toOneBacklink(
          5,
          object.id,
          (StrongsEntry srcObject) => srcObject.verse,
        ): object.strongsEntries,
        obx_int.RelInfo<Footnote>.toOneBacklink(
          4,
          object.id,
          (Footnote srcObject) => srcObject.verse,
        ): object.footnotes,
      },
      getId: (Verse object) => object.id,
      setId: (Verse object, int id) {
        object.id = id;
      },
      objectToFB: (Verse object, fb.Builder fbb) {
        final textOffset = fbb.writeString(object.text);
        fbb.startTable(5);
        fbb.addInt64(0, object.id);
        fbb.addInt64(1, object.verseNumber);
        fbb.addOffset(2, textOffset);
        fbb.addInt64(3, object.chapter.targetId);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final verseNumberParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          6,
          0,
        );
        final textParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 8, '');
        final object = Verse(
          id: idParam,
          verseNumber: verseNumberParam,
          text: textParam,
        );
        object.chapter.targetId = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          10,
          0,
        );
        object.chapter.attach(store);
        obx_int.InternalToManyAccess.setRelInfo<Verse>(
          object.strongsEntries,
          store,
          obx_int.RelInfo<StrongsEntry>.toOneBacklink(
            5,
            object.id,
            (StrongsEntry srcObject) => srcObject.verse,
          ),
        );
        obx_int.InternalToManyAccess.setRelInfo<Verse>(
          object.footnotes,
          store,
          obx_int.RelInfo<Footnote>.toOneBacklink(
            4,
            object.id,
            (Footnote srcObject) => srcObject.verse,
          ),
        );
        return object;
      },
    ),
  };

  return obx_int.ModelDefinition(model, bindings);
}

/// [BibleVersion] entity fields to define ObjectBox queries.
class BibleVersion_ {
  /// See [BibleVersion.id].
  static final id = obx.QueryIntegerProperty<BibleVersion>(
    _entities[0].properties[0],
  );

  /// See [BibleVersion.name].
  static final name = obx.QueryStringProperty<BibleVersion>(
    _entities[0].properties[1],
  );

  /// See [BibleVersion.languageCode].
  static final languageCode = obx.QueryStringProperty<BibleVersion>(
    _entities[0].properties[2],
  );

  /// see [BibleVersion.books]
  static final books = obx.QueryBacklinkToMany<Book, BibleVersion>(
    Book_.bibleVersion,
  );
}

/// [BiblesDownload] entity fields to define ObjectBox queries.
class BiblesDownload_ {
  /// See [BiblesDownload.id].
  static final id = obx.QueryIntegerProperty<BiblesDownload>(
    _entities[1].properties[0],
  );

  /// See [BiblesDownload.name].
  static final name = obx.QueryStringProperty<BiblesDownload>(
    _entities[1].properties[1],
  );

  /// See [BiblesDownload.shortTitle].
  static final shortTitle = obx.QueryStringProperty<BiblesDownload>(
    _entities[1].properties[2],
  );

  /// See [BiblesDownload.url].
  static final url = obx.QueryStringProperty<BiblesDownload>(
    _entities[1].properties[3],
  );
}

/// [Book] entity fields to define ObjectBox queries.
class Book_ {
  /// See [Book.id].
  static final id = obx.QueryIntegerProperty<Book>(_entities[2].properties[0]);

  /// See [Book.name].
  static final name = obx.QueryStringProperty<Book>(_entities[2].properties[1]);

  /// See [Book.bookId].
  static final bookId = obx.QueryStringProperty<Book>(
    _entities[2].properties[2],
  );

  /// See [Book.bibleVersion].
  static final bibleVersion = obx.QueryRelationToOne<Book, BibleVersion>(
    _entities[2].properties[3],
  );

  /// see [Book.chapters]
  static final chapters = obx.QueryBacklinkToMany<Chapter, Book>(Chapter_.book);
}

/// [Chapter] entity fields to define ObjectBox queries.
class Chapter_ {
  /// See [Chapter.id].
  static final id = obx.QueryIntegerProperty<Chapter>(
    _entities[3].properties[0],
  );

  /// See [Chapter.chapterNumber].
  static final chapterNumber = obx.QueryIntegerProperty<Chapter>(
    _entities[3].properties[1],
  );

  /// See [Chapter.book].
  static final book = obx.QueryRelationToOne<Chapter, Book>(
    _entities[3].properties[2],
  );

  /// see [Chapter.verses]
  static final verses = obx.QueryBacklinkToMany<Verse, Chapter>(Verse_.chapter);
}

/// [CreatedTopicsEn] entity fields to define ObjectBox queries.
class CreatedTopicsEn_ {
  /// See [CreatedTopicsEn.id].
  static final id = obx.QueryIntegerProperty<CreatedTopicsEn>(
    _entities[4].properties[0],
  );

  /// See [CreatedTopicsEn.title].
  static final title = obx.QueryStringProperty<CreatedTopicsEn>(
    _entities[4].properties[1],
  );

  /// See [CreatedTopicsEn.verses].
  static final verses = obx.QueryStringVectorProperty<CreatedTopicsEn>(
    _entities[4].properties[2],
  );
}

/// [CrossReference] entity fields to define ObjectBox queries.
class CrossReference_ {
  /// See [CrossReference.id].
  static final id = obx.QueryIntegerProperty<CrossReference>(
    _entities[5].properties[0],
  );

  /// See [CrossReference.verse].
  static final verse = obx.QueryStringProperty<CrossReference>(
    _entities[5].properties[1],
  );

  /// See [CrossReference.toVerse].
  static final toVerse = obx.QueryStringProperty<CrossReference>(
    _entities[5].properties[2],
  );
}

/// [Footnote] entity fields to define ObjectBox queries.
class Footnote_ {
  /// See [Footnote.id].
  static final id = obx.QueryIntegerProperty<Footnote>(
    _entities[6].properties[0],
  );

  /// See [Footnote.caller].
  static final caller = obx.QueryStringProperty<Footnote>(
    _entities[6].properties[1],
  );

  /// See [Footnote.text].
  static final text = obx.QueryStringProperty<Footnote>(
    _entities[6].properties[2],
  );

  /// See [Footnote.verse].
  static final verse = obx.QueryRelationToOne<Footnote, Verse>(
    _entities[6].properties[3],
  );
}

/// [GeneratedTopicsEn] entity fields to define ObjectBox queries.
class GeneratedTopicsEn_ {
  /// See [GeneratedTopicsEn.id].
  static final id = obx.QueryIntegerProperty<GeneratedTopicsEn>(
    _entities[7].properties[0],
  );

  /// See [GeneratedTopicsEn.title].
  static final title = obx.QueryStringProperty<GeneratedTopicsEn>(
    _entities[7].properties[1],
  );

  /// See [GeneratedTopicsEn.verses].
  static final verses = obx.QueryStringVectorProperty<GeneratedTopicsEn>(
    _entities[7].properties[2],
  );
}

/// [GoArea] entity fields to define ObjectBox queries.
class GoArea_ {
  /// See [GoArea.id].
  static final id = obx.QueryIntegerProperty<GoArea>(
    _entities[8].properties[0],
  );

  /// See [GoArea.name].
  static final name = obx.QueryStringProperty<GoArea>(
    _entities[8].properties[1],
  );

  /// See [GoArea.latitudes].
  static final latitudes = obx.QueryDoubleVectorProperty<GoArea>(
    _entities[8].properties[2],
  );

  /// See [GoArea.longitudes].
  static final longitudes = obx.QueryDoubleVectorProperty<GoArea>(
    _entities[8].properties[3],
  );
}

/// [GoChurch] entity fields to define ObjectBox queries.
class GoChurch_ {
  /// See [GoChurch.id].
  static final id = obx.QueryIntegerProperty<GoChurch>(
    _entities[9].properties[0],
  );

  /// See [GoChurch.churchName].
  static final churchName = obx.QueryStringProperty<GoChurch>(
    _entities[9].properties[1],
  );

  /// See [GoChurch.pastorName].
  static final pastorName = obx.QueryStringProperty<GoChurch>(
    _entities[9].properties[2],
  );

  /// See [GoChurch.address].
  static final address = obx.QueryStringProperty<GoChurch>(
    _entities[9].properties[3],
  );

  /// See [GoChurch.phone].
  static final phone = obx.QueryStringProperty<GoChurch>(
    _entities[9].properties[4],
  );

  /// See [GoChurch.email].
  static final email = obx.QueryStringProperty<GoChurch>(
    _entities[9].properties[5],
  );

  /// See [GoChurch.latitude].
  static final latitude = obx.QueryDoubleProperty<GoChurch>(
    _entities[9].properties[6],
  );

  /// See [GoChurch.longitude].
  static final longitude = obx.QueryDoubleProperty<GoChurch>(
    _entities[9].properties[7],
  );

  /// See [GoChurch.financialStatus].
  static final financialStatus = obx.QueryStringProperty<GoChurch>(
    _entities[9].properties[8],
  );

  /// see [GoChurch.notes]
  static final notes = obx.QueryRelationToMany<GoChurch, GoChurchNote>(
    _entities[9].relations[0],
  );
}

/// [GoChurchNote] entity fields to define ObjectBox queries.
class GoChurchNote_ {
  /// See [GoChurchNote.id].
  static final id = obx.QueryIntegerProperty<GoChurchNote>(
    _entities[10].properties[0],
  );

  /// See [GoChurchNote.content].
  static final content = obx.QueryStringProperty<GoChurchNote>(
    _entities[10].properties[1],
  );

  /// See [GoChurchNote.createdAt].
  static final createdAt = obx.QueryDateProperty<GoChurchNote>(
    _entities[10].properties[2],
  );

  /// See [GoChurchNote.updatedAt].
  static final updatedAt = obx.QueryDateProperty<GoChurchNote>(
    _entities[10].properties[3],
  );

  /// See [GoChurchNote.church].
  static final church = obx.QueryRelationToOne<GoChurchNote, GoChurch>(
    _entities[10].properties[4],
  );
}

/// [GoContact] entity fields to define ObjectBox queries.
class GoContact_ {
  /// See [GoContact.id].
  static final id = obx.QueryIntegerProperty<GoContact>(
    _entities[11].properties[0],
  );

  /// See [GoContact.fullName].
  static final fullName = obx.QueryStringProperty<GoContact>(
    _entities[11].properties[1],
  );

  /// See [GoContact.latitude].
  static final latitude = obx.QueryDoubleProperty<GoContact>(
    _entities[11].properties[2],
  );

  /// See [GoContact.longitude].
  static final longitude = obx.QueryDoubleProperty<GoContact>(
    _entities[11].properties[3],
  );

  /// See [GoContact.address].
  static final address = obx.QueryStringProperty<GoContact>(
    _entities[11].properties[4],
  );

  /// See [GoContact.birthday].
  static final birthday = obx.QueryStringProperty<GoContact>(
    _entities[11].properties[5],
  );

  /// See [GoContact.phone].
  static final phone = obx.QueryStringProperty<GoContact>(
    _entities[11].properties[6],
  );

  /// See [GoContact.email].
  static final email = obx.QueryStringProperty<GoContact>(
    _entities[11].properties[7],
  );

  /// See [GoContact.isVisited].
  static final isVisited = obx.QueryBooleanProperty<GoContact>(
    _entities[11].properties[8],
  );

  /// See [GoContact.eternalStatus].
  static final eternalStatus = obx.QueryStringProperty<GoContact>(
    _entities[11].properties[9],
  );

  /// see [GoContact.notes]
  static final notes = obx.QueryRelationToMany<GoContact, GoContactNote>(
    _entities[11].relations[0],
  );
}

/// [GoContactNote] entity fields to define ObjectBox queries.
class GoContactNote_ {
  /// See [GoContactNote.id].
  static final id = obx.QueryIntegerProperty<GoContactNote>(
    _entities[12].properties[0],
  );

  /// See [GoContactNote.content].
  static final content = obx.QueryStringProperty<GoContactNote>(
    _entities[12].properties[1],
  );

  /// See [GoContactNote.createdAt].
  static final createdAt = obx.QueryDateProperty<GoContactNote>(
    _entities[12].properties[2],
  );

  /// See [GoContactNote.updatedAt].
  static final updatedAt = obx.QueryDateProperty<GoContactNote>(
    _entities[12].properties[3],
  );

  /// See [GoContactNote.contact].
  static final contact = obx.QueryRelationToOne<GoContactNote, GoContact>(
    _entities[12].properties[4],
  );
}

/// [GoMapInfo] entity fields to define ObjectBox queries.
class GoMapInfo_ {
  /// See [GoMapInfo.id].
  static final id = obx.QueryIntegerProperty<GoMapInfo>(
    _entities[13].properties[0],
  );

  /// See [GoMapInfo.name].
  static final name = obx.QueryStringProperty<GoMapInfo>(
    _entities[13].properties[1],
  );

  /// See [GoMapInfo.filePath].
  static final filePath = obx.QueryStringProperty<GoMapInfo>(
    _entities[13].properties[2],
  );

  /// See [GoMapInfo.downloadUrl].
  static final downloadUrl = obx.QueryStringProperty<GoMapInfo>(
    _entities[13].properties[3],
  );

  /// See [GoMapInfo.isTemporary].
  static final isTemporary = obx.QueryBooleanProperty<GoMapInfo>(
    _entities[13].properties[4],
  );

  /// See [GoMapInfo.latitude].
  static final latitude = obx.QueryDoubleProperty<GoMapInfo>(
    _entities[13].properties[5],
  );

  /// See [GoMapInfo.longitude].
  static final longitude = obx.QueryDoubleProperty<GoMapInfo>(
    _entities[13].properties[6],
  );

  /// See [GoMapInfo.zoomLevel].
  static final zoomLevel = obx.QueryIntegerProperty<GoMapInfo>(
    _entities[13].properties[7],
  );
}

/// [GoMinistry] entity fields to define ObjectBox queries.
class GoMinistry_ {
  /// See [GoMinistry.id].
  static final id = obx.QueryIntegerProperty<GoMinistry>(
    _entities[14].properties[0],
  );

  /// See [GoMinistry.ministryName].
  static final ministryName = obx.QueryStringProperty<GoMinistry>(
    _entities[14].properties[1],
  );

  /// See [GoMinistry.contactName].
  static final contactName = obx.QueryStringProperty<GoMinistry>(
    _entities[14].properties[2],
  );

  /// See [GoMinistry.address].
  static final address = obx.QueryStringProperty<GoMinistry>(
    _entities[14].properties[3],
  );

  /// See [GoMinistry.phone].
  static final phone = obx.QueryStringProperty<GoMinistry>(
    _entities[14].properties[4],
  );

  /// See [GoMinistry.email].
  static final email = obx.QueryStringProperty<GoMinistry>(
    _entities[14].properties[5],
  );

  /// See [GoMinistry.latitude].
  static final latitude = obx.QueryDoubleProperty<GoMinistry>(
    _entities[14].properties[6],
  );

  /// See [GoMinistry.longitude].
  static final longitude = obx.QueryDoubleProperty<GoMinistry>(
    _entities[14].properties[7],
  );

  /// See [GoMinistry.partnerStatus].
  static final partnerStatus = obx.QueryStringProperty<GoMinistry>(
    _entities[14].properties[8],
  );

  /// see [GoMinistry.notes]
  static final notes = obx.QueryRelationToMany<GoMinistry, GoMinistryNote>(
    _entities[14].relations[0],
  );
}

/// [GoMinistryNote] entity fields to define ObjectBox queries.
class GoMinistryNote_ {
  /// See [GoMinistryNote.id].
  static final id = obx.QueryIntegerProperty<GoMinistryNote>(
    _entities[15].properties[0],
  );

  /// See [GoMinistryNote.content].
  static final content = obx.QueryStringProperty<GoMinistryNote>(
    _entities[15].properties[1],
  );

  /// See [GoMinistryNote.createdAt].
  static final createdAt = obx.QueryDateProperty<GoMinistryNote>(
    _entities[15].properties[2],
  );

  /// See [GoMinistryNote.updatedAt].
  static final updatedAt = obx.QueryDateProperty<GoMinistryNote>(
    _entities[15].properties[3],
  );

  /// See [GoMinistryNote.ministry].
  static final ministry = obx.QueryRelationToOne<GoMinistryNote, GoMinistry>(
    _entities[15].properties[4],
  );
}

/// [GoStreet] entity fields to define ObjectBox queries.
class GoStreet_ {
  /// See [GoStreet.id].
  static final id = obx.QueryIntegerProperty<GoStreet>(
    _entities[16].properties[0],
  );

  /// See [GoStreet.name].
  static final name = obx.QueryStringProperty<GoStreet>(
    _entities[16].properties[1],
  );

  /// See [GoStreet.latitudes].
  static final latitudes = obx.QueryDoubleVectorProperty<GoStreet>(
    _entities[16].properties[2],
  );

  /// See [GoStreet.longitudes].
  static final longitudes = obx.QueryDoubleVectorProperty<GoStreet>(
    _entities[16].properties[3],
  );

  /// See [GoStreet.type].
  static final type = obx.QueryStringProperty<GoStreet>(
    _entities[16].properties[4],
  );
}

/// [GoZone] entity fields to define ObjectBox queries.
class GoZone_ {
  /// See [GoZone.id].
  static final id = obx.QueryIntegerProperty<GoZone>(
    _entities[17].properties[0],
  );

  /// See [GoZone.name].
  static final name = obx.QueryStringProperty<GoZone>(
    _entities[17].properties[1],
  );

  /// See [GoZone.latitude].
  static final latitude = obx.QueryDoubleProperty<GoZone>(
    _entities[17].properties[2],
  );

  /// See [GoZone.longitude].
  static final longitude = obx.QueryDoubleProperty<GoZone>(
    _entities[17].properties[3],
  );

  /// See [GoZone.widthInMeters].
  static final widthInMeters = obx.QueryDoubleProperty<GoZone>(
    _entities[17].properties[4],
  );

  /// See [GoZone.heightInMeters].
  static final heightInMeters = obx.QueryDoubleProperty<GoZone>(
    _entities[17].properties[5],
  );
}

/// [StrongsEntry] entity fields to define ObjectBox queries.
class StrongsEntry_ {
  /// See [StrongsEntry.id].
  static final id = obx.QueryIntegerProperty<StrongsEntry>(
    _entities[18].properties[0],
  );

  /// See [StrongsEntry.strongsNumber].
  static final strongsNumber = obx.QueryStringProperty<StrongsEntry>(
    _entities[18].properties[1],
  );

  /// See [StrongsEntry.word].
  static final word = obx.QueryStringProperty<StrongsEntry>(
    _entities[18].properties[2],
  );

  /// See [StrongsEntry.position].
  static final position = obx.QueryIntegerProperty<StrongsEntry>(
    _entities[18].properties[3],
  );

  /// See [StrongsEntry.verse].
  static final verse = obx.QueryRelationToOne<StrongsEntry, Verse>(
    _entities[18].properties[4],
  );
}

/// [UserPreferences] entity fields to define ObjectBox queries.
class UserPreferences_ {
  /// See [UserPreferences.id].
  static final id = obx.QueryIntegerProperty<UserPreferences>(
    _entities[19].properties[0],
  );

  /// See [UserPreferences.currentMap].
  static final currentMap = obx.QueryStringProperty<UserPreferences>(
    _entities[19].properties[1],
  );

  /// See [UserPreferences.fontFamily].
  static final fontFamily = obx.QueryStringProperty<UserPreferences>(
    _entities[19].properties[2],
  );

  /// See [UserPreferences.fontSize].
  static final fontSize = obx.QueryDoubleProperty<UserPreferences>(
    _entities[19].properties[3],
  );

  /// See [UserPreferences.languageCode].
  static final languageCode = obx.QueryStringProperty<UserPreferences>(
    _entities[19].properties[4],
  );

  /// See [UserPreferences.currentBibleVersionId].
  static final currentBibleVersionId =
      obx.QueryIntegerProperty<UserPreferences>(_entities[19].properties[5]);
}

/// [Verse] entity fields to define ObjectBox queries.
class Verse_ {
  /// See [Verse.id].
  static final id = obx.QueryIntegerProperty<Verse>(
    _entities[20].properties[0],
  );

  /// See [Verse.verseNumber].
  static final verseNumber = obx.QueryIntegerProperty<Verse>(
    _entities[20].properties[1],
  );

  /// See [Verse.text].
  static final text = obx.QueryStringProperty<Verse>(
    _entities[20].properties[2],
  );

  /// See [Verse.chapter].
  static final chapter = obx.QueryRelationToOne<Verse, Chapter>(
    _entities[20].properties[3],
  );

  /// see [Verse.strongsEntries]
  static final strongsEntries = obx.QueryBacklinkToMany<StrongsEntry, Verse>(
    StrongsEntry_.verse,
  );

  /// see [Verse.footnotes]
  static final footnotes = obx.QueryBacklinkToMany<Footnote, Verse>(
    Footnote_.verse,
  );
}
