import 'package:by_faith/objectbox.g.dart'; // Generated by `flutter pub run build_runner build`
import 'package:by_faith/features/go/models/go_model.dart';

late Store store;
late Box<GoContact> goContactsBox;

Future<void> setupObjectBox() async {
  try {
    store = await openStore();
    goContactsBox = store.box<GoContact>();
  } catch (e) {
    print('ObjectBox initialization error: $e');
    rethrow; // Rethrow to allow calling code to handle the error
  }
}